# Generated by Django 5.1.4 on 2026-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical (tracked inventory)'), ('service', 'Service (no inventory)'), ('digital', 'Digital (no inventory)')], db_index=True, default='physical', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('carton', 'Carton'), ('case', 'Case'), ('litre', 'Litre'), ('unit', 'Unit'), ('hour', 'Hour'), ('day', 'Day'), ('kg', 'Kilogram'), ('piece', 'Piece')], default='bottle', max_length=20),
        ),
    ]
