# Generated by Django 5.1.4 on 2026-03-15 14:08

import apps.core.models
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_owner_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_cost_price',
            field=apps.core.models.MoneyField(decimal_places=4, default=Decimal('0'), help_text="Owner's actual purchase cost — visible to owners only for margin analytics", max_digits=15),
        ),
    ]
