# Generated by Django 5.1.4 on 2026-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_inventory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this item on the public storefront.'),
        ),
    ]
