# Generated by Django 5.1.4 on 2026-08-20 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_backfill_control_account_flags'),
        ('inventory', '0011_modifiergroup_modifieroption'),
        ('tax', '0008_capitalallowanceclaim_asset_and_more'),
        ('tenancy', '0037_organisation_receipt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'name'), name='uniq_inventory_category_org_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'sku'), name='uniq_inventory_product_org_sku'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'name'), name='uniq_inventory_warehouse_org_name'),
        ),
    ]
