# Generated by Django 5.1.4 on 2026-08-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_account_unique_together_and_more'),
        ('inventory', '0012_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='GL cost-of-sales account for this item. Leave blank to use the organisation default.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_cogs_account', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_account',
            field=models.ForeignKey(blank=True, help_text="GL revenue account for this item's sales. Leave blank to use the organisation default.", limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_sales_account', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='wages_account',
            field=models.ForeignKey(blank=True, help_text='Service products only — GL wages/direct-labor account debited on a sale instead of cogs_account.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_wages_account', to='accounting.account'),
        ),
    ]
