# Generated by Django 5.1.4 on 2026-08-29 17:37

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_cogs_account_product_sales_account_and_more'),
        ('tenancy', '0038_add_enabled_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costing_method',
            field=models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('average', 'Average'), ('specific', 'Specific Unit')], default='average', help_text='How cost of goods sold is determined for this item on a sale.', max_length=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='average_cost',
            field=apps.core.models.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=15),
        ),
        migrations.CreateModel(
            name='StockCostLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['product', 'warehouse', 'created_at'], name='inventory_s_product_e27b51_idx')],
            },
        ),
    ]
