# Generated by Django 5.1.4 on 2026-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_costing_method_stockitem_average_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_symbology',
            field=models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean8', 'EAN-8'), ('ean13', 'EAN-13'), ('upc', 'UPC')], default='code128', help_text='Format the barcode is encoded/printed as. Only affects generation and scanning, not the stored value.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive (tax added on top)'), ('inclusive', 'Inclusive (tax already in the price)')], default='exclusive', help_text="Whether this item's price already includes tax, or tax is added on top at sale.", max_length=10),
        ),
    ]
