# Generated by Django 5.1.4 on 2026-08-30 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_productimage'),
        ('tenancy', '0038_add_enabled_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='Set on a variant row to link it to its Variable Product template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Display attributes for this variant, e.g. {"Size": "Large", "Color": "Red"}.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical (tracked inventory)'), ('service', 'Service (no inventory)'), ('digital', 'Digital (no inventory)'), ('variable', 'Variable (has variants)'), ('combo', 'Combo / Bundle')], db_index=True, default='physical', max_length=20),
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='How many units of the component one combo unit consumes.', max_digits=12)),
                ('combo_product', models.ForeignKey(help_text='The Combo Product this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='combo_components', to='inventory.product')),
                ('component_product', models.ForeignKey(help_text='The underlying product consumed when the combo is sold.', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_combos', to='inventory.product')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('combo_product', 'component_product'), name='uniq_combo_component_per_combo')],
            },
        ),
    ]
