# Generated by Django 5.1.4 on 2026-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_variants_and_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Up to 5 free-form label:value pairs, e.g. {"Warranty": "12 months"}.'),
        ),
    ]
