# Generated by Django 5.1.4 on 2026-02-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="purchase_receipts/"
            ),
        ),
    ]
