# Generated by Django 5.1.4 on 2026-07-25 19:52

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_hsn_digitax'),
        ('purchases', '0004_purchaseorder_supplier_nullable'),
        ('suppliers', '0002_supplier_opening_balance'),
        ('tenancy', '0032_alter_organisation_strict_gl_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('refund_method', models.CharField(choices=[('ap', 'Reduce Payable (debit note)'), ('cash', 'Cash Refund'), ('bank', 'Bank Refund')], default='ap', max_length=10)),
                ('subtotal', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('tax_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('total_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('gl_post_status', models.CharField(default='pending', max_length=20)),
                ('gl_post_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='suppliers.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-return_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('line_total', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='purchases.purchaseorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
