# Generated by Django 5.1.4 on 2026-08-28 04:12

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
