# Generated by Django 5.1.15 on 2026-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseorder_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='billed_before_receipt',
            field=models.BooleanField(default=False),
        ),
    ]
