# Generated by Django 5.1.4 on 2026-02-27 16:01

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quote_number", models.CharField(editable=False, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("sent", "sent"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                            ("converted", "converted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "subtotal",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "discount_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "tax_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                (
                    "converted_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote",
                        to="sales.invoice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="customers.customer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organisation", "quote_number")},
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit_price",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_total",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
