# Generated by Django 5.1.4 on 2026-08-20 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_unique_together_and_more'),
        ('inventory', '0012_alter_category_unique_together_and_more'),
        ('quotes', '0001_initial'),
        ('sales', '0021_saleitem_modifiers'),
        ('tenancy', '0037_organisation_receipt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'quote_number'), name='uniq_quote_org_quote_number'),
        ),
    ]
