# Generated by Django 5.1.4 on 2026-06-01 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ai_recon_match'),
        ('tenancy', '0027_sandbox_testing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Mapping',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref__gt', ''), ('source_type__gt', '')), fields=('organisation', 'source_type', 'source_ref'), name='unique_journal_source'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='accounts_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_ap', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='accounts_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_ar', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_bank', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='bank_charges_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_bank_charges', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_cash', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_cogs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='general_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_general_expense', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_inventory', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='paye_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_paye', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='pension_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_pension', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_revenue', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='salary_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_salary', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='vat_input_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_vat_input', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='vat_output_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_vat_output', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='wht_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_wht', to='accounting.account'),
        ),
    ]
