# Generated by Django 5.1.4 on 2026-07-22 14:43

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_journal_immutability_trigger'),
        ('tenancy', '0029_add_annual_turnover_to_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Cost of Sales', 'Cost of Sales'), ('Indirect Cost', 'Indirect Cost'), ('Expenses', 'Expenses'), ('Asset', 'Asset'), ('Cash & Cash Equivalent', 'Cash & Cash Equivalent'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity')], max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='allow_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountSubType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('account_group', models.CharField(choices=[('Income', 'Income'), ('Cost of Sales', 'Cost of Sales'), ('Indirect Cost', 'Indirect Cost'), ('Expenses', 'Expenses'), ('Asset', 'Asset'), ('Cash & Cash Equivalent', 'Cash & Cash Equivalent'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity')], max_length=40)),
                ('base_account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('cogs', 'Cost of Goods Sold')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['account_group', 'name'],
                'unique_together': {('organisation', 'account_group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.accountsubtype'),
        ),
    ]
