# Generated by Django 5.1.4 on 2026-07-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_seed_subtypes_backfill_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='approval_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approval_status',
            field=models.CharField(choices=[('none', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='journal_attachments/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_signed', to=settings.AUTH_USER_MODEL),
        ),
    ]
