# Generated by Django 5.1.4 on 2026-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_journalentry_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='account_attachments/'),
        ),
    ]
