# Generated by Django 5.1.4 on 2026-07-24 08:42

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='capitalisation_source',
            field=models.CharField(choices=[('direct', 'Direct purchase'), ('bill', 'Capitalised from bill'), ('opening_balance', 'Opening balance / take-on')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='funding_source',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('payable', 'Accounts Payable'), ('equity', 'Owner / Capital Introduced'), ('none', 'Already on books (opening balance)')], default='bank', max_length=12),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='input_tax_amount',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='input_tax_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='qualifying_cost',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='source_document_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
