# Generated by Django 5.1.4 on 2026-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_journalentry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_convention',
            field=models.CharField(choices=[('full_month', 'Full month'), ('pro_rata', 'Pro-rata (by days)')], default='full_month', max_length=12),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='reducing_balance_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='total_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('reducing_balance', 'Reducing Balance'), ('immediate', 'Immediate Write-Off'), ('zero', 'No Depreciation (0%)'), ('units', 'Units of Production')], default='straight_line', max_length=20),
        ),
    ]
