# Generated by Django 5.1.4 on 2026-07-24 09:44

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_fixedasset_depreciation_convention_and_more'),
        ('inventory', '0008_product_hsn_digitax'),
        ('tenancy', '0030_organisation_fixed_asset_capitalisation_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='cost_centre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revaluation_date', models.DateField()),
                ('previous_carrying_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('new_carrying_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('surplus', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='accounting.fixedasset')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-revaluation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_date', models.DateField()),
                ('from_cost_centre', models.CharField(blank=True, default='', max_length=100)),
                ('to_cost_centre', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounting.fixedasset')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
