# Generated by Django 5.1.4 on 2026-07-24 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_fixedasset_cost_centre_fixedasset_location_and_more'),
        ('tenancy', '0031_organisation_capital_allowance_nta2025_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('land', 'land'), ('building', 'building'), ('vehicle', 'vehicle'), ('equipment', 'equipment'), ('furniture', 'furniture'), ('other', 'other')], default='other', max_length=20)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('reducing_balance', 'Reducing Balance'), ('immediate', 'Immediate Write-Off'), ('zero', 'No Depreciation (0%)'), ('units', 'Units of Production')], default='straight_line', max_length=20)),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('reducing_balance_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_type_acc_dep', to='accounting.account')),
                ('depreciation_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_type_dep_exp', to='accounting.account')),
                ('fixed_asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_type_fa', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounting.assettype'),
        ),
    ]
