# Generated by Django 5.1.4 on 2026-07-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_assettype_fixedasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapping',
            name='nhf_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_nhf', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.assettype'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.assettype'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='master_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_assets', to='accounting.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_convention',
            field=models.CharField(choices=[('full_month', 'Full month'), ('pro_rata', 'Pro-rata (by days)'), ('new_month', 'New month (start the month after purchase)')], default='full_month', max_length=12),
        ),
    ]
