# Generated by Django 5.1.4 on 2026-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_backfill_control_account_flags'),
        ('inventory', '0012_alter_category_unique_together_and_more'),
        ('tenancy', '0037_organisation_receipt_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fixedasset',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'code'), name='uniq_account_org_code'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'code'), name='uniq_asset_type_org_code'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'asset_code'), name='uniq_fixed_asset_org_asset_code'),
        ),
    ]
