# Generated by Django 5.1.4 on 2026-08-30 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_account_unique_together_and_more'),
        ('tenancy', '0038_add_enabled_payment_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClassGLDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('physical', 'Physical (tracked inventory)'), ('service', 'Service (no inventory)'), ('digital', 'Digital (no inventory)'), ('variable', 'Variable (has variants)'), ('combo', 'Combo / Bundle')], max_length=20)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_class_cogs_defaults', to='accounting.account')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_class_inventory_defaults', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_class_sales_defaults', to='accounting.account')),
                ('wages_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_class_wages_defaults', to='accounting.account')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'product_type'), name='uniq_item_class_gl_default_per_type')],
            },
        ),
    ]
