# Generated by Django 5.1.15 on 2026-09-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_item_class_gl_defaults_and_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapping',
            name='shipping_income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_shipping_income', to='accounting.account'),
        ),
    ]
