# Generated by Django 5.1.15 on 2026-09-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_accountmapping_shipping_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapping',
            name='goods_in_transit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_goods_in_transit', to='accounting.account'),
        ),
    ]
