# Generated by Django 5.1.4 on 2026-08-17 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_alter_webhooksubscription_options'),
        ('tenancy', '0036_membership_granted_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('leave', 'Leave'), ('payroll', 'Payroll'), ('sales', 'Sales'), ('bills', 'Bills'), ('inventory', 'Inventory'), ('tax', 'Tax'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('no_connector', 'No mailbox connected')], default='not_requested', max_length=20)),
                ('email_error', models.TextField(blank=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='integrations.domainevent')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('leave', 'Leave'), ('payroll', 'Payroll'), ('sales', 'Sales'), ('bills', 'Bills'), ('inventory', 'Inventory'), ('tax', 'Tax'), ('system', 'System')], max_length=20)),
                ('email_enabled', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='tenancy.membership')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'ordering': ['category'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('membership', 'category'), name='uniq_notification_pref_per_membership_category')],
            },
        ),
    ]
