# Generated by Django 5.1.4 on 2026-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('leave', 'Leave'), ('payroll', 'Payroll'), ('sales', 'Sales'), ('bills', 'Bills'), ('inventory', 'Inventory'), ('tax', 'Tax'), ('system', 'System'), ('messages', 'Messages')], db_index=True, default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('leave', 'Leave'), ('payroll', 'Payroll'), ('sales', 'Sales'), ('bills', 'Bills'), ('inventory', 'Inventory'), ('tax', 'Tax'), ('system', 'System'), ('messages', 'Messages')], max_length=20),
        ),
    ]
