# Generated by Django 5.1.4 on 2026-03-03 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveSmallIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='Stored plain-text — use app passwords', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='tenancy.organisation')),
            ],
            options={
                'verbose_name': 'Email Config',
            },
        ),
    ]
