# Generated by Django 5.1.4 on 2026-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_add_email_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_sort_code",
            field=models.CharField(
                blank=True, help_text="Sort code or routing number", max_length=20
            ),
        ),
    ]
