# Generated by Django 5.1.4 on 2026-03-10 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_organisation_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('sales', 'Sales / Invoices'), ('purchases', 'Purchase Orders'), ('bills', 'Bills / Payables'), ('expenses', 'Expenses'), ('inventory', 'Inventory'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('accounting', 'Accounting'), ('tax', 'Tax'), ('budget', 'Budget'), ('quotes', 'Quotes'), ('recurring', 'Recurring Invoices')], max_length=30)),
                ('access_level', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('write', 'Enter & Save'), ('edit', 'Full Edit')], default='edit', max_length=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='tenancy.membership')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'unique_together': {('membership', 'module')},
            },
        ),
    ]
