# Generated by Django 5.1.4 on 2026-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0006_organisation_brand_color_use_letterhead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="letterhead",
            field=models.FileField(
                blank=True,
                help_text="Optional letterhead file (image, PDF, or DOC) shown at the top of invoices and PDF documents",
                null=True,
                upload_to="org_letterheads/",
            ),
        ),
    ]
