# Generated by Django 5.1.4 on 2026-03-15 08:55

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_letterhead_filefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_password",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted at rest — use app passwords",
                max_length=255,
            ),
        ),
    ]
