# Generated by Django 5.1.4 on 2026-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0008_encrypt_smtp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="company_name_font",
            field=models.CharField(
                choices=[
                    ("helvetica", "Helvetica (Modern)"),
                    ("times", "Times New Roman (Classic)"),
                    ("courier", "Courier (Typewriter)"),
                ],
                default="helvetica",
                help_text="Font used for the company name on invoices and PDF documents",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="invoice_company_name",
            field=models.CharField(
                blank=True,
                help_text="Override the company name shown on invoices/PDFs. Leave blank to use the organisation name.",
                max_length=255,
            ),
        ),
    ]
