# Generated by Django 5.1.4 on 2026-03-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_add_company_stamp_remove_letterhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales / Invoices'), ('purchases', 'Purchase Orders'), ('bills', 'Bills / Payables'), ('expenses', 'Expenses'), ('inventory', 'Inventory'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('accounting', 'Accounting'), ('tax', 'Tax'), ('budget', 'Budget'), ('quotes', 'Quotes'), ('recurring', 'Recurring Invoices'), ('settings', 'Settings (Company / Billing)')], max_length=30),
        ),
    ]
