# Generated by Django 5.1.4 on 2026-03-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_add_show_company_name_on_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
