# Generated by Django 5.1.4 on 2026-04-01 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0016_partner_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerclientlink",
            options={"ordering": ["-created_at"], "verbose_name": "Partner Client"},
        ),
        migrations.AlterModelOptions(
            name="partnerprofile",
            options={"ordering": ["-created_at"], "verbose_name": "Partner Profile"},
        ),
        migrations.AlterField(
            model_name="partnerclientlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partnerclientlink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
