# Generated by Django 5.1.4 on 2026-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0017_alter_partnerclientlink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprofile",
            name="referral_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, unique=True
            ),
        ),
    ]
