# Generated by Django 5.1.4 on 2026-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0019_organisation_multi_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="entity_group_name",
            field=models.CharField(
                blank=True,
                help_text="Short label for this entity within the group (e.g. 'Lagos Branch', 'Holdings').",
                max_length=100,
            ),
        ),
    ]
