# Generated by Django 5.1.4 on 2026-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0026_commission_partner_invoice_whitelabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneraccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner Access Request'},
        ),
        migrations.AlterModelOptions(
            name='whitelabelconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'White-label Config'},
        ),
        migrations.RenameIndex(
            model_name='commissionledger',
            new_name='tenancy_com_partner_4d5282_idx',
            old_name='comm_ledger_partner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionledger',
            new_name='tenancy_com_referen_1eb99b_idx',
            old_name='comm_ledger_reference_idx',
        ),
        migrations.AlterField(
            model_name='commissionledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='partneraccessrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='partneraccessrequest',
            name='invite_token',
            field=models.UUIDField(blank=True, db_index=True, help_text='One-time token generated by the org owner to invite a specific partner.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partneraccessrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Optional reason given by the org owner when rejecting.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partneraccessrequest',
            name='request_message',
            field=models.CharField(blank=True, help_text='Optional message from the partner to the org owner.', max_length=300),
        ),
        migrations.AlterField(
            model_name='partnerinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='partnerinvoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='whitelabelconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
