# Generated by Django 5.1.4 on 2026-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0027_sandbox_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='strict_gl_mode',
            field=models.BooleanField(default=False),
        ),
    ]
