# Generated by Django 5.1.4 on 2026-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0027_sandbox_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
