# Generated by Django 5.1.4 on 2026-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0028_add_strict_gl_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Declared annual turnover (NGN). Used for WHT small-payer exemption threshold.', max_digits=20, null=True),
        ),
    ]
