# Generated by Django 5.1.4 on 2026-07-24 09:44

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0029_add_annual_turnover_to_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='fixed_asset_capitalisation_threshold',
            field=apps.core.models.MoneyField(decimal_places=4, default=100000, max_digits=15),
        ),
        migrations.AddField(
            model_name='organisation',
            name='fixed_asset_revaluation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
