# Generated by Django 5.1.4 on 2026-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0030_organisation_fixed_asset_capitalisation_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='capital_allowance_nta2025_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
