# Generated by Django 5.1.4 on 2026-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0031_organisation_capital_allowance_nta2025_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='strict_gl_mode',
            field=models.BooleanField(default=True),
        ),
    ]
