# Generated by Django 5.1.4 on 2026-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0032_alter_organisation_strict_gl_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(choices=[('general', 'General / Retail'), ('restaurant', 'Restaurant / Bar / Hotel'), ('pharmacy', 'Pharmacy / Supermarket'), ('laundry', 'Laundry'), ('services', 'Services')], default='general', max_length=20),
        ),
    ]
