# Generated by Django 5.1.4 on 2026-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0033_organisation_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('employee', 'Employee (self-service)')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('employee', 'Employee (self-service)')], default='staff', max_length=20),
        ),
    ]
