# Generated by Django 5.1.4 on 2026-08-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0034_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraccessrequest',
            name='scope',
            field=models.CharField(choices=[('operational', 'Operational (full advisory access)'), ('messaging_only', 'Messaging Only'), ('both', 'Operational + Messaging')], default='operational', help_text="What access this request grants once approved. 'messaging_only' provisions a PARTNER_CONTACT membership (in-app messaging only, no operational data access); 'operational' and 'both' preserve the existing accountant-role provisioning behaviour.", max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('employee', 'Employee (self-service)'), ('partner_contact', 'Partner Contact (messaging only)')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('employee', 'Employee (self-service)'), ('partner_contact', 'Partner Contact (messaging only)')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales / Invoices'), ('purchases', 'Purchase Orders'), ('bills', 'Bills / Payables'), ('expenses', 'Expenses'), ('inventory', 'Inventory'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('payroll', 'HR / Payroll'), ('leave', 'Leave'), ('reports', 'Reports'), ('accounting', 'Accounting'), ('tax', 'Tax'), ('budget', 'Budget'), ('quotes', 'Quotes'), ('recurring', 'Recurring Invoices'), ('settings', 'Settings (Company / Billing)')], max_length=30),
        ),
    ]
