# Generated by Django 5.1.4 on 2026-08-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0035_partneraccessrequest_scope_alter_invitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='granted_scope',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
