# Generated by Django 5.1.4 on 2026-08-22 07:49

import apps.tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0037_organisation_receipt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='enabled_payment_types',
            field=models.JSONField(default=apps.tenancy.models.default_enabled_payment_types),
        ),
    ]
