# Generated by Django 5.1.4 on 2026-08-01 10:19

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_product_is_published'),
        ('pos', '0003_tillsession_gl_post_error_tillsession_gl_post_status'),
        ('sales', '0020_salepayment_till_session'),
        ('tenancy', '0033_organisation_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(help_text='The address customers use, e.g. audity.app/s/kates-stores', unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$', 'Use 3–50 lowercase letters, numbers or hyphens.')])),
                ('is_published', models.BooleanField(default=False, help_text="Off means the page returns 'not found' to the public.")),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('delivery_note', models.CharField(blank=True, help_text="e.g. 'Delivery within Ikeja, ₦1,500'.", max_length=200)),
                ('accent_colour', models.CharField(blank=True, default='#12694A', max_length=9)),
                ('accepts_orders', models.BooleanField(default=True)),
                ('minimum_order', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('hide_out_of_stock', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorefrontOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(db_index=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='placed', max_length=12)),
                ('fulfilment', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('table', 'Table service')], default='pickup', max_length=10)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('subtotal', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('total', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_orders', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('pos_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_orders', to='pos.posorder')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storefront.storefront')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_orders', to='pos.restauranttable')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorefrontOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('line_total', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.storefrontorder')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_order_items', to='inventory.product')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='storefrontorder',
            index=models.Index(fields=['organisation', 'status'], name='storefront__organis_66ee15_idx'),
        ),
    ]
