# Generated by Django 5.1.4 on 2026-08-22 08:03

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='fixed_delivery_charge',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Flat delivery fee added at checkout for delivery orders, unless the free-delivery threshold is met.', max_digits=15),
        ),
        migrations.AddField(
            model_name='storefront',
            name='free_delivery_threshold',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=None, help_text='Orders at or above this subtotal skip the delivery charge. Blank means no free-delivery rule.', max_digits=15, null=True),
        ),
    ]
