# Generated by Django 5.1.4 on 2026-05-19 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0002_firssubmission_credit_note_fields'),
        ('sales', '0014_invoice_firs_fields'),
        ('tenancy', '0027_sandbox_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('pass', 'Pass Batch (valid invoices)'), ('fail', 'Fail Batch (invalid payloads)')], help_text='Whether this batch targets pass or fail certification.', max_length=10)),
                ('target_count', models.PositiveSmallIntegerField(default=50, help_text='How many submissions this batch aimed to make.')),
                ('completed_count', models.PositiveSmallIntegerField(default=0, help_text='How many submissions completed (pass + fail outcomes combined).')),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='running', max_length=10)),
                ('error_detail', models.TextField(blank=True, help_text='Top-level error if the batch failed before completing.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sandbox Test Run',
                'verbose_name_plural': 'Sandbox Test Runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='firssubmission',
            new_name='einvoicing__invoice_5ff2c2_idx',
            old_name='einvoicing_invoice_status_idx',
        ),
        migrations.RenameIndex(
            model_name='firssubmission',
            new_name='einvoicing__organis_9bba12_idx',
            old_name='einvoicing_org_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='firssubmission',
            new_name='einvoicing__submiss_49daf3_idx',
            old_name='einvoicing_submission_ref_idx',
        ),
        migrations.AddField(
            model_name='firssubmission',
            name='is_sandbox_test',
            field=models.BooleanField(db_index=True, default=False, help_text='True for synthetic submissions created by the sandbox test runner. FIRS requires 50 pass + 50 fail sandbox tests before production access.'),
        ),
        migrations.AlterField(
            model_name='firssubmission',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Null only for sandbox certification test rows (is_sandbox_test=True).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firs_submissions', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='firssubmission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AddIndex(
            model_name='firssubmission',
            index=models.Index(fields=['organisation', 'is_sandbox_test', 'status'], name='einvoicing__organis_1a0571_idx'),
        ),
        migrations.AddField(
            model_name='sandboxtestrun',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
    ]
