# Generated by Django 5.1.4 on 2026-02-23 14:46

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Nigeria Personal Income Tax 2024",
                        max_length=200,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("income", "Income Tax"),
                            ("corporate", "Corporate Tax"),
                            ("vat", "VAT / Sales Tax"),
                            ("withholding", "Withholding Tax"),
                            ("excise", "Excise Duty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code", max_length=2
                    ),
                ),
                (
                    "tax_year",
                    models.PositiveSmallIntegerField(help_text="Applicable tax year"),
                ),
                (
                    "is_progressive",
                    models.BooleanField(
                        default=True,
                        help_text="True = tiered brackets. False = flat rate.",
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Used only if is_progressive=False",
                        max_digits=5,
                    ),
                ),
                (
                    "personal_allowance",
                    apps.core.models.MoneyField(
                        decimal_places=4,
                        default=0,
                        help_text="Tax-free allowance before bracket calculation begins",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Configuration",
                "abstract": False,
                "unique_together": {("organisation", "name", "tax_year")},
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lower_bound",
                    apps.core.models.MoneyField(
                        decimal_places=4,
                        default=0,
                        help_text="Income at which this bracket starts",
                        max_digits=15,
                    ),
                ),
                (
                    "upper_bound",
                    apps.core.models.MoneyField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Income at which this bracket ends (null = no upper limit)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate for income in this bracket",
                        max_digits=5,
                    ),
                ),
                (
                    "cumulative_tax_below",
                    apps.core.models.MoneyField(
                        decimal_places=4,
                        default=0,
                        help_text="Total tax owed on all income below lower_bound (pre-computed for speed)",
                        max_digits=15,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="tax.taxconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Bracket",
                "ordering": ["lower_bound"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage (e.g., 7.5 for 7.5%)",
                        max_digits=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Classes",
                "abstract": False,
                "unique_together": {("organisation", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("filed", "Filed"),
                            ("paid", "Paid"),
                            ("amended", "Amended"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_taxable_income",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "total_allowances",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "net_taxable_income",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "tax_payable",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "tax_paid",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "tax_due",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="tax.taxconfig",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Return",
                "abstract": False,
                "unique_together": {
                    ("organisation", "config", "period_start", "period_end")
                },
            },
        ),
    ]
