# Generated by Django 5.1.4 on 2026-02-27 16:01

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExciseDuty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("spirits", "spirits"),
                            ("wine", "wine"),
                            ("beer", "beer"),
                            ("tobacco", "tobacco"),
                            ("other", "other"),
                        ],
                        default="spirits",
                        max_length=20,
                    ),
                ),
                (
                    "duty_type",
                    models.CharField(
                        choices=[
                            ("specific", "Specific (per LPA)"),
                            ("ad_valorem", "Ad Valorem (%)"),
                        ],
                        default="specific",
                        max_length=20,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="WHTRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_type", models.CharField(max_length=200)),
                (
                    "company_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "individual_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["transaction_type"],
                "unique_together": {("organisation", "transaction_type")},
            },
        ),
        migrations.CreateModel(
            name="WHTTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("purchase", "Purchase")],
                        max_length=20,
                    ),
                ),
                ("counterparty_name", models.CharField(max_length=200)),
                ("tin", models.CharField(blank=True, max_length=50)),
                (
                    "gross_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "wht_rate_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "wht_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                (
                    "net_amount",
                    apps.core.models.MoneyField(
                        decimal_places=4, default=0, max_digits=15
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("withheld", "Withheld"), ("remitted", "Remitted")],
                        default="withheld",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "wht_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tax.whtrate"
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
    ]
