# Generated by Django 5.1.4 on 2026-07-02 11:56

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_capital_allowances_deferred_tax_transfer_pricing'),
        ('tenancy', '0028_add_strict_gl_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capitalallowanceclaim',
            name='unique_capital_allowance_per_asset_year',
        ),
        migrations.RemoveConstraint(
            model_name='taxobligation',
            name='unique_tax_obligation_per_org_period',
        ),
        migrations.AddField(
            model_name='taxclass',
            name='treatment',
            field=models.CharField(choices=[('standard', 'Standard Rate'), ('zero_rated', 'Zero-Rated'), ('exempt', 'Exempt')], default='standard', help_text='VAT treatment: standard (7.5%), zero-rated (0% but input recoverable), exempt (0%, input NOT recoverable)', max_length=20),
        ),
        migrations.AlterField(
            model_name='capitalallowanceclaim',
            name='cost',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Original acquisition cost', max_digits=15),
        ),
        migrations.AlterField(
            model_name='capitalallowanceclaim',
            name='initial_allowance_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IA rate % (only in year of acquisition)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='capitalallowanceclaim',
            name='opening_tax_written_down_value',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Tax WDV at start of this tax year', max_digits=15),
        ),
        migrations.AlterField(
            model_name='capitalallowanceclaim',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='deferredtaxitem',
            name='deferred_tax_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='timing_difference × tax_rate / 100', max_digits=15),
        ),
        migrations.AlterField(
            model_name='deferredtaxitem',
            name='is_recognised',
            field=models.BooleanField(default=True, help_text='Unrecognised DTAs may not meet recoverability criteria'),
        ),
        migrations.AlterField(
            model_name='deferredtaxitem',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='deferredtaxitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Applicable corporate tax rate % for computing the deferred tax amount', max_digits=5),
        ),
        migrations.AlterField(
            model_name='deferredtaxitem',
            name='timing_difference',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Carrying amount minus tax base (positive = DTL, negative = DTA)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='adjustment_required',
            field=models.BooleanField(default=False, help_text="True if actual price deviates from arm's length"),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Total value of this transaction type for the year', max_digits=15),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='arm_length_price',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text="Arm's length price / benchmark value", max_digits=15),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='country',
            field=models.CharField(help_text='ISO country code of related party', max_length=2),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='related_party_name',
            field=models.CharField(help_text='Name of related party (subsidiary, parent, affiliate)', max_length=300),
        ),
        migrations.AlterField(
            model_name='relatedpartytransaction',
            name='relationship',
            field=models.CharField(help_text='e.g. Parent Company, Subsidiary, Sister Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxobligation',
            name='label',
            field=models.CharField(help_text="e.g. 'VAT Return — January 2025'", max_length=200),
        ),
        migrations.AlterField(
            model_name='taxobligation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='taxobligation',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Null for annual obligations', null=True),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='counterparty_name',
            field=models.CharField(blank=True, help_text='Customer or supplier name', max_length=200),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='counterparty_tin',
            field=models.CharField(blank=True, help_text='TIN for ITC verification', max_length=50),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='is_claimable',
            field=models.BooleanField(default=True, help_text='Input VAT is claimable only if for business use with valid tax invoice'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='net_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Net amount before VAT', max_digits=15),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='period_start',
            field=models.DateField(help_text='VAT return period this transaction belongs to'),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Invoice number or bill reference', max_length=200),
        ),
        migrations.AlterField(
            model_name='vattransaction',
            name='vat_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='VAT amount charged or paid', max_digits=15),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='remittance_reference',
            field=models.CharField(blank=True, help_text='FIRS receipt / TaxPro MAX payment reference', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='capitalallowanceclaim',
            unique_together={('organisation', 'asset_name', 'tax_year')},
        ),
        migrations.AlterUniqueTogether(
            name='taxobligation',
            unique_together={('organisation', 'obligation_type', 'period_year', 'period_month')},
        ),
    ]
