# Generated by Django 5.1.4 on 2026-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_add_treatment_to_taxclass'),
        ('tenancy', '0029_add_annual_turnover_to_organisation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taxconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organisation', 'tax_type', 'tax_year'), name='unique_active_taxconfig_per_type_year'),
        ),
    ]
