# Generated by Django 5.1.4 on 2026-07-24 10:33

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_fixedasset_cost_centre_fixedasset_location_and_more'),
        ('tax', '0007_add_taxconfig_unique_constraint'),
        ('tenancy', '0031_organisation_capital_allowance_nta2025_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalallowanceclaim',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_allowance_claims', to='accounting.fixedasset'),
        ),
        migrations.AddField(
            model_name='capitalallowanceclaim',
            name='notional_floor',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='1% of qualifying cost retained until disposal', max_digits=15),
        ),
        migrations.AddField(
            model_name='capitalallowanceclaim',
            name='qualifying_cost',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, help_text='Capital-allowance cost base (§27(2))', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='capitalallowanceclaim',
            name='initial_allowance_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abolished under NTA 2025 — always 0', max_digits=5),
        ),
        migrations.CreateModel(
            name='CARateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('asset_class', models.CharField(choices=[('industrial_building', 'Industrial Building'), ('non_industrial_building', 'Non-Industrial Building'), ('plant_machinery', 'Plant & Machinery'), ('motor_vehicle', 'Motor Vehicle'), ('furniture', 'Furniture & Fittings'), ('computer', 'Computer & IT Equipment'), ('other', 'Other')], max_length=30)),
                ('annual_rate', models.DecimalField(decimal_places=2, help_text='Straight-line annual %', max_digits=5)),
                ('notional_rate', models.DecimalField(decimal_places=2, default=1, help_text='Notional cost % retained until disposal', max_digits=5)),
                ('signed_off_by', models.CharField(blank=True, default='', help_text='Practitioner who signed off this rate version', max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-effective_from', 'asset_class'],
                'unique_together': {('organisation', 'effective_from', 'asset_class')},
            },
        ),
    ]
