# Generated by Django 5.1.4 on 2026-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_owner_action',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
