# Generated by Django 5.1.4 on 2026-03-07 10:26

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='previous_price',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, help_text='Previous/old price for comparison', max_digits=15, null=True),
        ),
    ]
