# Generated by Django 5.1.4 on 2026-03-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensegroup_deleted_at'),
        ('tenancy', '0007_letterhead_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
    ]
