# Generated by Django 5.1.4 on 2026-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_gl_post_error_expense_gl_post_status'),
        ('tenancy', '0037_organisation_receipt_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'name'), name='uniq_expense_category_org_name'),
        ),
    ]
