# Generated by Django 5.1.4 on 2026-08-26 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_account_unique_together_and_more'),
        ('expenses', '0008_alter_expensecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='accounting.account'),
        ),
    ]
