# Generated by Django 5.1.4 on 2026-03-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_bankreconciliation_bankreconciliationline_and_more"),
        ("bills", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bill_items",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="billitem",
            name="expense_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bill_items",
                to="expenses.expensecategory",
            ),
        ),
    ]
