# Generated by Django 5.1.4 on 2026-03-10 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billitem_account_billitem_expense_category'),
        ('tenancy', '0003_organisation_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('folder_date', models.DateField(blank=True, help_text='Date for this folder (optional)', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bills.billfolder')),
            ],
            options={
                'ordering': ['-folder_date', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='bills.billfolder'),
        ),
    ]
