# Generated by Django 5.1.4 on 2026-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_gl_post_error_bill_gl_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='asset_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='capitalise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
