# Generated by Django 5.1.4 on 2026-08-20 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_billitem_asset_category_billitem_capitalise_and_more'),
        ('suppliers', '0004_alter_supplier_unique_together_and_more'),
        ('tenancy', '0037_organisation_receipt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'bill_number'), name='uniq_bill_org_bill_number'),
        ),
    ]
