# Generated by Django 5.1.4 on 2026-08-28 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_unique_together_and_more'),
        ('purchases', '0006_purchaseorder_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='source_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_from_po', to='purchases.purchaseorder'),
        ),
    ]
