import { useEffect, useRef, useState } from 'react'
import { confirmDialog } from '@/lib/dialog'
import { useSearchParams } from 'react-router-dom'
import { useDataRefresh } from '@/hooks/useDataRefresh'
import { useModuleAccess } from '@/hooks/useModuleAccess'
import { usePagination } from '@/hooks/usePagination'
import Pagination from '@/components/Pagination'
import { Plus, Search, Package, AlertTriangle, X, Pencil, Loader2, TrendingUp, TrendingDown, History, Maximize2, Minimize2, ShieldCheck, FileDown, Table2, ArrowDownCircle, Trash2, RefreshCw, CheckSquare, ChevronDown, Upload } from 'lucide-react'
import toast from 'react-hot-toast'
import { inventoryApi, taxApi, salesApi, bypassNextGets } from '@/services/api'
import { formatCurrency, formatAmountInput, stripCommas, formatDate } from '@/lib/utils'
import AmountInput from '@/components/AmountInput'
import { useAuthStore } from '@/store/authStore'
import type { Product, ProductImage, ProductVariantSummary, ComboComponent, TaxClass, Organisation } from '@/types'
import SortSelect from '@/components/SortSelect'
import { FieldTooltip } from '@/components/FieldTooltip'
import DateInput from '@/components/DateInput'
import GLAccountSelect from '@/components/GLAccountSelect'
// @ts-ignore
import autoTable from 'jspdf-autotable'
import jsPDF from 'jspdf'

async function exportProductsPDF(products: Product[], org?: Organisation | null) {
  const { saveBlobFile } = await import('@/lib/saveBlobFile')
  const { applyDocHeader, buildTableStyle, addDocFooter, pdfMoney, COLORS, TYPE } = await import('@/lib/pdfUtils')
  const toRgb = (hex?: string): [number, number, number] => {
    const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex ?? '')
    if (!m) return [249, 115, 22]
    return [parseInt(m[1], 16), parseInt(m[2], 16), parseInt(m[3], 16)]
  }
  const BRAND = toRgb(org?.brand_color) as [number, number, number]
  const DARK  = COLORS.DARK
  const MUTED = COLORS.MUTED
  const tmpl  = org?.invoice_template ?? 'classic'
  const pdfFont = 'helvetica'
  const displayName = org?.name ?? 'Company'
  const exportedAt = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' })
  doc.setLineHeightFactor(1.15)
  const pageW = doc.internal.pageSize.getWidth()
  let logoData: string | undefined
  const _storedLogo = useAuthStore.getState().logoDataUrl
  if (_storedLogo) { logoData = _storedLogo }
  else if (org?.logo) { try { const r = await fetch(org.logo); const b = await r.blob(); logoData = await new Promise(res => { const fr = new FileReader(); fr.onload = () => res(fr.result as string); fr.readAsDataURL(b) }) } catch { /* skip */ } }
  const y = applyDocHeader(doc, {
    tmpl, pageW, BRAND, DARK, MUTED,
    landscape: true,
    logoData, displayName,
    orgAddress: org?.address, orgEmail: org?.email, orgPhone: org?.phone,
    pdfFont, fontSize: 12, pdfStyle: 'bold', nameColor: tmpl === 'modern' ? DARK : COLORS.WHITE,
    showCompanyName: true, docTitle: 'PRODUCT CATALOGUE',
    metaRows: [
      ['Total Products', String(products.length)],
      ['Exported', exportedAt],
    ],
  })
  const ts = buildTableStyle(BRAND, pdfFont, { landscape: true })
  autoTable(doc, {
    ...ts,
    startY: y,
    tableWidth: 'auto',
    head: [['SKU', 'Product', 'Type', 'Cost Price', 'Selling Price', 'Wholesale Price', 'Stock']],
    body: products.map(p => {
      const cost = parseFloat(p.cost_price) || 0
      const sell = parseFloat(p.selling_price) || 0
      return [
        p.sku ?? '—', p.name, (p as any).product_type ?? 'physical',
        pdfMoney(cost),
        pdfMoney(sell),
        (p as any).wholesale_price && parseFloat((p as any).wholesale_price) > 0
          ? pdfMoney(parseFloat((p as any).wholesale_price)) : '—',
        p.total_stock ?? 0,
      ]
    }),
    columnStyles: {
      0: { cellWidth: 'auto' },                            // SKU
      1: { cellWidth: 'auto' },                            // Product
      2: { cellWidth: 'auto' },                            // Type
      3: { cellWidth: 'auto', halign: 'right' as const }, // Cost Price
      4: { cellWidth: 'auto', halign: 'right' as const }, // Selling Price
      5: { cellWidth: 'auto', halign: 'right' as const }, // Wholesale Price
      6: { cellWidth: 'auto', halign: 'right' as const }, // Stock
    },
    styles: { ...ts.styles, fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
    margin: { left: 10, right: 10 },
  })
  const finalY = (doc as any).lastAutoTable.finalY + 4
  doc.setFontSize(TYPE.TINY.size); doc.setFont(pdfFont, 'normal'); doc.setTextColor(...MUTED)
  doc.text(`Report generated by Audity  ·  ${exportedAt}`, 10, finalY)
  addDocFooter(doc, { orgName: displayName, docTitle: 'PRODUCT CATALOGUE', docRef: '', BRAND, pdfFont, landscape: true })
  await saveBlobFile(doc.output('blob'), `products-catalogue.pdf`)
}

async function exportProductsCSV(products: Product[]) {
  const { saveBlobFile } = await import('@/lib/saveBlobFile')
  const headers = ['SKU', 'Product', 'Type', 'Cost Price', 'Selling Price', 'Wholesale Price', 'Stock']
  const rows = products.map(p => {
    const cost = parseFloat(p.cost_price) || 0
    const sell = parseFloat(p.selling_price) || 0
    return [p.sku ?? '', p.name, (p as any).product_type ?? 'physical', cost, sell,
      (p as any).wholesale_price && parseFloat((p as any).wholesale_price) > 0 ? parseFloat((p as any).wholesale_price) : '',
      p.total_stock ?? 0]
  })
  const csv = [headers, ...rows].map(r => r.map(v => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n')
  await saveBlobFile(new Blob([csv], { type: 'text/csv' }), 'products-catalogue.csv')
}

async function exportProductsExcel(products: Product[]) {
  const { saveBlobFile } = await import('@/lib/saveBlobFile')
  const XLSX = await import('xlsx')
  const headers = ['SKU', 'Product', 'Type', 'Cost Price', 'Selling Price', 'Wholesale Price', 'Stock']
  const rows = products.map(p => {
    const cost = parseFloat(p.cost_price) || 0
    const sell = parseFloat(p.selling_price) || 0
    return [p.sku ?? '', p.name, (p as any).product_type ?? 'physical', cost, sell,
      (p as any).wholesale_price && parseFloat((p as any).wholesale_price) > 0 ? parseFloat((p as any).wholesale_price) : '',
      p.total_stock ?? 0]
  })
  const allRows = [headers, ...rows]
  const ws = XLSX.utils.aoa_to_sheet(allRows)
  // Auto-size each column to fit its widest cell
  ws['!cols'] = headers.map((_, ci) => ({
    wch: Math.max(...allRows.map(r => String(r[ci] ?? '').length)) + 2,
  }))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Products')
  const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  await saveBlobFile(new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'products-catalogue.xlsx')
}

interface SalesHistoryItem {
  invoice_id: string
  invoice_number: string
  issue_date: string
  customer_name: string
  sold_by: string
  warehouse: string
  payment_method: string
  quantity: string
  unit_price: string
  line_total: string
  status: string
}

async function exportHistoryPDF(items: SalesHistoryItem[], product: Product, org?: Organisation | null) {
  const { saveBlobFile } = await import('@/lib/saveBlobFile')
  const { applyDocHeader, buildTableStyle, addDocFooter, pdfMoney, pdfQty, COLORS, TYPE } = await import('@/lib/pdfUtils')
  const hexToRgb = (hex?: string): [number,number,number] => {
    const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex ?? '')
    if (!m) return [249, 115, 22]; return [parseInt(m[1],16), parseInt(m[2],16), parseInt(m[3],16)]
  }
  const BRAND: [number,number,number] = hexToRgb(org?.brand_color)
  const DARK   = COLORS.DARK
  const MUTED  = COLORS.MUTED
  const tmpl   = org?.invoice_template ?? 'classic'
  const pdfFont = org?.company_name_font?.toLowerCase().includes('times') ? 'times'
    : org?.company_name_font?.toLowerCase().includes('courier') ? 'courier' : 'helvetica'
  const isBold   = org?.company_name_font_bold !== false
  const isItalic = org?.company_name_font_italic === true
  const pdfStyle = isBold && isItalic ? 'bolditalic' : isBold ? 'bold' : isItalic ? 'italic' : 'normal'
  const fontSize  = Math.max(8, Math.min(36, org?.company_name_font_size ?? 12))
  const nameColor: [number,number,number] = (() => {
    const c = org?.company_name_font_color
    if (!c || c === '#ffffff') return (tmpl === 'modern' || tmpl === 'minimal') ? DARK : COLORS.WHITE
    return hexToRgb(c)
  })()
  const displayName = org?.invoice_company_name?.trim() || org?.name || 'Audity'

  const { urlToDataUrl } = await import('@/services/api')
  const { useAuthStore: _authStore } = await import('@/store/authStore')
  let logoData: string | null = null
  const _storedLogo2 = _authStore.getState().logoDataUrl
  if (_storedLogo2) { logoData = _storedLogo2 }
  else if (org?.logo) { try { logoData = await urlToDataUrl(org.logo) } catch { /* skip */ } }

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' })
  doc.setLineHeightFactor(1.15)
  const pageW = doc.internal.pageSize.getWidth()
  const exportedAt = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })

  const y = applyDocHeader(doc, {
    tmpl, pageW, BRAND, DARK, MUTED,
    landscape: true,
    logoData,
    displayName,
    orgAddress: org?.address,
    orgEmail:   org?.email,
    orgPhone:   org?.phone,
    pdfFont,
    fontSize,
    pdfStyle,
    nameColor,
    showCompanyName: org?.show_company_name_on_pdf !== false,
    companyFontUnderline: org?.company_name_font_underline,
    docTitle: 'TRANSACTION HISTORY',
    metaRows: [
      ['Product',  product.name],
      ['SKU',      product.sku],
      ['Exported', exportedAt],
    ],
  })

  const ts = buildTableStyle(BRAND, pdfFont, { landscape: true })
  autoTable(doc, {
    ...ts,
    startY: y,
    head: [['Reference', 'Date', 'Customer', 'Sold By', 'Location', 'Payment', 'Qty', 'Unit Price', 'Total', 'Status']],
    body: items.map((i) => [
      i.invoice_number,
      formatDate(i.issue_date),
      i.customer_name,
      i.sold_by,
      i.warehouse,
      i.payment_method.replace('_', ' '),
      pdfQty(i.quantity),
      pdfMoney(i.unit_price),
      pdfMoney(i.line_total),
      i.status,
    ]),
    styles: { ...ts.styles, fontSize: 7.5 },
    headStyles: { ...ts.headStyles, fontSize: 7 },
    columnStyles: {
      0: { cellWidth: 32 },                              // Invoice No
      1: { cellWidth: 22 },                              // Date
      6: { cellWidth: 12, halign: 'center' as const },  // Qty
      7: { cellWidth: 26, halign: 'right' as const },   // Unit Price
      8: { cellWidth: 26, halign: 'right' as const, fontStyle: 'bold' as const },  // Total
      9: { cellWidth: 20 },                              // Status
    },
  })

  const finalY = (doc as any).lastAutoTable.finalY + 4
  doc.setFontSize(TYPE.TINY.size); doc.setFont(pdfFont, 'normal'); doc.setTextColor(...MUTED)
  doc.text(`Report generated by Audity  ·  ${exportedAt}`, 10, finalY)

  addDocFooter(doc, { orgName: displayName, docTitle: 'TRANSACTION HISTORY', docRef: product.sku, BRAND, pdfFont, landscape: true })
  await saveBlobFile(doc.output('blob'), `transaction-history-${product.sku}.pdf`)
}

async function exportHistoryCSV(items: SalesHistoryItem[], product: Product) {
  const { saveBlobFile } = await import('@/lib/saveBlobFile')
  const headers = ['Reference', 'Date', 'Customer', 'Sold By', 'Location', 'Payment', 'Qty', 'Unit Price', 'Total', 'Status']
  const rows = items.map((i) => [
    i.invoice_number,
    formatDate(i.issue_date),
    i.customer_name,
    i.sold_by,
    i.warehouse,
    i.payment_method.replace('_', ' '),
    i.quantity,
    i.unit_price,
    i.line_total,
    i.status,
  ])
  const csv = [headers, ...rows].map((r) => r.map((v) => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  await saveBlobFile(blob, `transaction-history-${product.sku}.csv`)
}

const BLANK = {
  sku: '', name: '', brand: '', unit_of_measure: 'unit',
  product_type: 'physical',
  cost_price: '', owner_cost_price: '', selling_price: '', wholesale_price: '',
  reorder_level: '10', max_stock_level: '', quantity_in_pack: '1',
  alcohol_percentage: '', volume_ml: '',
  is_taxable: false, tax_class: '', tax_type: 'exclusive',
  inventory_account: '', sales_account: '', cogs_account: '', wages_account: '',
  costing_method: 'average',
  is_active: true,
  description: '', barcode: '', barcode_symbology: 'code128', category: '',
  parent_product: '', variant_attributes: {} as Record<string, string>,
}

const BLANK_BATCH = {
  quantity: '',
  warehouse: '',
  batch_number: '',
  manufacture_date: '',
  expiry_date: '',
  as_of_date: new Date().toISOString().slice(0, 10),
}

const PRODUCT_TYPES = [
  { value: 'physical', label: 'Physical (tracked inventory)' },
  { value: 'service', label: 'Service (no inventory)' },
  { value: 'digital', label: 'Digital (no inventory)' },
  { value: 'variable', label: 'Variable Product (has variants)' },
  { value: 'combo', label: 'Combo / Bundle Product' },
]

// Mirrors Product.CostingMethod on the backend.
const COSTING_METHODS = [
  { value: 'average', label: 'Average' },
  { value: 'fifo', label: 'FIFO' },
  { value: 'lifo', label: 'LIFO' },
  { value: 'specific', label: 'Specific Unit' },
]

// Mirrors Product.TaxType on the backend.
const TAX_TYPES = [
  { value: 'exclusive', label: 'Exclusive (tax added on top)' },
  { value: 'inclusive', label: 'Inclusive (tax already in the price)' },
]

// Mirrors Product.BarcodeSymbology on the backend.
const BARCODE_SYMBOLOGIES = [
  { value: 'code128', label: 'Code 128' },
  { value: 'code39', label: 'Code 39' },
  { value: 'ean8', label: 'EAN-8' },
  { value: 'ean13', label: 'EAN-13' },
  { value: 'upc', label: 'UPC' },
]

const UNITS_OF_MEASURE = [
  'bottle', 'carton', 'case', 'dozen', 'litre', 'pack', 'unit', 'hour', 'day', 'kg', 'piece',
]

export default function ProductsPage() {
  const { user, memberRole, planModules, organisation } = useAuthStore()
  const { canEdit } = useModuleAccess('inventory')
  const isOwner = memberRole === 'owner' || memberRole === 'admin' || user?.is_superuser === true
  // Owner-only features (cost price, owner column) hidden on Starter — single-user plan doesn't need them
  const showOwnerFeatures = isOwner && (planModules === null || planModules.includes('owner_analytics'))
  const [products, setProducts] = useState<Product[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  // True once the edit form has been hydrated from the DETAIL endpoint. The
  // products LIST is slim (no description/barcode/wholesale/max_stock/pack), so
  // saving an un-hydrated form must not send those fields or it would blank them.
  const [editHydrated, setEditHydrated] = useState(false)
  const editReqRef = useRef<string>('')
  const [saving, setSaving] = useState(false)
  const [galleryImages, setGalleryImages] = useState<ProductImage[]>([])
  const [galleryUploading, setGalleryUploading] = useState(false)
  const [dragImageId, setDragImageId] = useState<string | null>(null)
  const [variantList, setVariantList] = useState<ProductVariantSummary[]>([])
  const [comboComponentsList, setComboComponentsList] = useState<ComboComponent[]>([])
  const [newVariant, setNewVariant] = useState({ sku: '', name: '', attributes: '', cost_price: '', selling_price: '' })
  const [newCombo, setNewCombo] = useState({ component_product: '', quantity: '1' })
  const [comboSaving, setComboSaving] = useState(false)
  const [variantSaving, setVariantSaving] = useState(false)
  const [comboPickableProducts, setComboPickableProducts] = useState<Product[]>([])
  const [customFieldRows, setCustomFieldRows] = useState<{ label: string; value: string }[]>([])
  const [form, setForm] = useState({ ...BLANK })
  const [taxClasses, setTaxClasses] = useState<TaxClass[]>([])
  const [sortBy, setSortBy] = useState('name')
  const [historySort, setHistorySort] = useState('-issue_date')
  const [historyProduct, setHistoryProduct] = useState<Product | null>(null)
  const [historyItems, setHistoryItems] = useState<SalesHistoryItem[]>([])
  const [historyLoading, setHistoryLoading] = useState(false)
  const [historySearch, setHistorySearch] = useState('')
  const [historyFullscreen, setHistoryFullscreen] = useState(false)
  const [historyDateFrom, setHistoryDateFrom] = useState('')
  const [historyDateTo, setHistoryDateTo] = useState('')
  const [batchForm, setBatchForm] = useState({ ...BLANK_BATCH })
  const [warehouses, setWarehouses] = useState<{ id: string; name: string }[]>([])
  const [editWarehouse, setEditWarehouse] = useState('')
  const [editOrigWarehouse, setEditOrigWarehouse] = useState('')
  const [editOrigQty, setEditOrigQty] = useState(0)
  const [editStockQty, setEditStockQty] = useState('')
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [refreshing, setRefreshing] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  const [showDeleteAll, setShowDeleteAll] = useState(false)
  const [deletingAll, setDeletingAll] = useState(false)
  const [categories, setCategories] = useState<{ id: string; name: string }[]>([])
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [bulkDeleting, setBulkDeleting] = useState(false)
  const { page, setPage, pageSize, setPageSize, totalPages, paged, total } = usePagination(products)

  const fetchProducts = async () => {
    try {
      const { data } = await inventoryApi.products({ search, ordering: sortBy, page_size: 9999 })
      setProducts(data.results ?? data)
    } catch {
      toast.error('Failed to load products')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchProducts() }, [search, sortBy])
  useDataRefresh(fetchProducts)

  useEffect(() => {
    taxApi.classes().then(({ data }) => setTaxClasses(data.results ?? data)).catch(() => {})
  }, [])

  const loadModalDeps = () => {
    inventoryApi.warehouses().then(({ data }) => {
      const list: { id: string; name: string; is_default?: boolean }[] = data.results ?? data
      setWarehouses(list)
      const def = list.find((w) => w.is_default) ?? list[0]
      if (def) setBatchForm((b) => ({ ...b, warehouse: def.id }))
    }).catch(() => {})
    inventoryApi.categories().then(({ data }) => {
      setCategories(data.results ?? data)
    }).catch(() => {})
    // Combo Products pick their components from physical stock items only —
    // a service/digital/variable-template/combo product can't be assembled from.
    inventoryApi.products({ product_type: 'physical', page_size: 500 }).then(({ data }) => {
      setComboPickableProducts(data.results ?? data)
    }).catch(() => {})
  }

  const openCreate = () => {
    setEditId(null)
    setForm({ ...BLANK })
    setBatchForm({ ...BLANK_BATCH })
    setGalleryImages([])
    setVariantList([])
    setComboComponentsList([])
    setNewVariant({ sku: '', name: '', attributes: '', cost_price: '', selling_price: '' })
    setNewCombo({ component_product: '', quantity: '1' })
    setCustomFieldRows([])
    loadModalDeps()
    setShowModal(true)
  }

  // Deep-link from Dashboard Quick Actions: /inventory/products?new=1 opens the New Product modal.
  const [searchParams, setSearchParams] = useSearchParams()
  useEffect(() => {
    if (searchParams.get('new') === '1') {
      openCreate()
      searchParams.delete('new')
      setSearchParams(searchParams, { replace: true })
    }
  }, [])

  const safeAmt = (v: string | null | undefined) => {
    const num = parseFloat(v ?? '0')
    if (isNaN(num)) return ''
    const normalized = num % 1 === 0 ? String(Math.round(num)) : String(num)
    return formatAmountInput(normalized)
  }

  const openEdit = (p: Product) => {
    setEditId(p.id)
    setForm({
      sku: p.sku ?? '',
      name: p.name ?? '',
      brand: (p.brand as string | null) ?? '',
      unit_of_measure: p.unit_of_measure ?? 'unit',
      product_type: (p as any).product_type ?? 'physical',
      cost_price: safeAmt(p.cost_price),
      owner_cost_price: safeAmt(p.owner_cost_price),
      selling_price: safeAmt(p.selling_price),
      wholesale_price: safeAmt((p as any).wholesale_price),
      reorder_level: String(p.reorder_level ?? 10),
      max_stock_level: String((p as any).max_stock_level ?? ''),
      quantity_in_pack: String((p as any).quantity_in_pack ?? '1'),
      alcohol_percentage: String(p.alcohol_percentage ?? ''),
      volume_ml: String(p.volume_ml ?? ''),
      is_taxable: p.is_taxable ?? false,
      tax_class: p.tax_class ?? '',
      tax_type: (p as any).tax_type ?? 'exclusive',
      inventory_account: p.inventory_account ?? '',
      costing_method: (p as any).costing_method ?? 'average',
      sales_account: (p as any).sales_account ?? '',
      cogs_account: (p as any).cogs_account ?? '',
      wages_account: (p as any).wages_account ?? '',
      is_active: p.is_active ?? true,
      description: (p as any).description ?? '',
      barcode: (p as any).barcode ?? '',
      barcode_symbology: (p as any).barcode_symbology ?? 'code128',
      category: (p as any).category ?? '',
      parent_product: (p as any).parent_product ?? '',
      variant_attributes: (p as any).variant_attributes ?? {},
    })
    loadModalDeps()
    // Hydrate the slim-list gaps from the detail endpoint (full serializer).
    // Row data renders instantly; these fields land a moment later.
    setEditHydrated(false)
    editReqRef.current = p.id
    inventoryApi.product(p.id).then(({ data }) => {
      if (editReqRef.current !== p.id) return  // user opened a different product meanwhile
      // EVERY field the slim list omits has to be patched here. Anything
      // missing shows its blank/default in the form, and because the save
      // guard below stops skipping fields once editHydrated flips true, that
      // default then overwrites the real stored value — silently wiping a
      // product's costing method or GL mapping just by opening and saving it.
      setForm((f) => ({
        ...f,
        description: data.description ?? '',
        barcode: data.barcode ?? '',
        wholesale_price: safeAmt(data.wholesale_price),
        max_stock_level: String(data.max_stock_level ?? ''),
        quantity_in_pack: String(data.quantity_in_pack ?? '1'),
        costing_method: data.costing_method ?? 'average',
        inventory_account: data.inventory_account ?? '',
        sales_account: data.sales_account ?? '',
        cogs_account: data.cogs_account ?? '',
        wages_account: data.wages_account ?? '',
        tax_type: data.tax_type ?? 'exclusive',
        barcode_symbology: data.barcode_symbology ?? 'code128',
        parent_product: data.parent_product ?? '',
        variant_attributes: data.variant_attributes ?? {},
      }))
      setGalleryImages(data.images ?? [])
      setVariantList(data.variants ?? [])
      setComboComponentsList(data.combo_components ?? [])
      setCustomFieldRows(
        Object.entries(data.custom_fields ?? {}).map(([label, value]) => ({ label, value: String(value) })),
      )
      setEditHydrated(true)
    }).catch(() => { /* offline — form keeps row data; save will omit slim gaps */ })
    // Fetch current warehouse for this product (largest stock qty wins)
    setEditWarehouse('')
    setEditOrigWarehouse('')
    setEditOrigQty(0)
    setEditStockQty('')
    inventoryApi.stock({ product: p.id }).then(({ data }) => {
      const items: any[] = (data.results ?? data).filter((i: any) => i.id !== null)
      if (items.length > 0) {
        const top = items.reduce((a: any, b: any) =>
          parseFloat(b.quantity_on_hand) > parseFloat(a.quantity_on_hand) ? b : a
        )
        setEditWarehouse(String(top.warehouse ?? ''))
        setEditOrigWarehouse(String(top.warehouse ?? ''))
        const qty = parseFloat(top.quantity_on_hand) || 0
        setEditOrigQty(qty)
        setEditStockQty(String(qty))
      } else {
        setEditStockQty('0')
      }
    }).catch(() => { setEditStockQty('0') })
    setShowModal(true)
  }

  const handleImageFilesSelected = async (files: FileList | null) => {
    if (!files || files.length === 0 || !editId) return
    setGalleryUploading(true)
    try {
      for (const file of Array.from(files)) {
        const resp = await inventoryApi.uploadProductImage(editId, file)
        if (resp.ok) {
          const img = await resp.json()
          setGalleryImages((imgs) => [...imgs, img])
        } else {
          toast.error('One or more images could not be uploaded')
        }
      }
    } finally {
      setGalleryUploading(false)
    }
  }

  const handleSetMainImage = async (imageId: string) => {
    setGalleryImages((imgs) => imgs.map((i) => ({ ...i, is_main: i.id === imageId })))
    try {
      await inventoryApi.setMainProductImage(imageId)
    } catch {
      toast.error('Could not set cover photo')
    }
  }

  const handleDeleteImage = async (imageId: string) => {
    const ok = await confirmDialog('Remove this image from the gallery?')
    if (!ok) return
    const removed = galleryImages.find((i) => i.id === imageId)
    setGalleryImages((imgs) => imgs.filter((i) => i.id !== imageId))
    try {
      await inventoryApi.deleteProductImage(imageId)
      // Deleting the cover photo promotes the next one server-side — reflect
      // that locally too instead of leaving no image marked main.
      if (removed?.is_main) {
        setGalleryImages((imgs) => imgs.map((i, idx) => (idx === 0 ? { ...i, is_main: true } : i)))
      }
    } catch {
      toast.error('Could not remove image')
    }
  }

  const handleImageDrop = async (targetId: string) => {
    if (!dragImageId || dragImageId === targetId) { setDragImageId(null); return }
    const from = galleryImages.findIndex((i) => i.id === dragImageId)
    const to = galleryImages.findIndex((i) => i.id === targetId)
    if (from === -1 || to === -1) { setDragImageId(null); return }
    const reordered = [...galleryImages]
    const [moved] = reordered.splice(from, 1)
    reordered.splice(to, 0, moved)
    setGalleryImages(reordered)
    setDragImageId(null)
    try {
      await inventoryApi.reorderProductImages(reordered.map((i) => i.id))
    } catch {
      toast.error('Could not save the new image order')
    }
  }

  const handleAddVariant = async () => {
    if (!editId || !newVariant.sku.trim() || !newVariant.name.trim()) {
      toast.error('SKU and name are required for a variant')
      return
    }
    setVariantSaving(true)
    try {
      const attributes: Record<string, string> = {}
      for (const pair of newVariant.attributes.split(',')) {
        const [k, v] = pair.split(':').map((s) => s.trim())
        if (k && v) attributes[k] = v
      }
      const { data } = await inventoryApi.createProduct({
        sku: newVariant.sku.trim(),
        name: newVariant.name.trim(),
        product_type: 'physical',
        parent_product: editId,
        variant_attributes: attributes,
        cost_price: stripCommas(newVariant.cost_price) || '0',
        selling_price: stripCommas(newVariant.selling_price) || '0',
        unit_of_measure: form.unit_of_measure,
      })
      setVariantList((v) => [...v, { ...data, total_stock: 0 }])
      setNewVariant({ sku: '', name: '', attributes: '', cost_price: '', selling_price: '' })
      toast.success('Variant added')
    } catch (err: any) {
      const apiErr = err?.response?.data?.error ?? err?.response?.data
      const msg = typeof apiErr === 'string' ? apiErr : (apiErr?.message ?? JSON.stringify(err?.response?.data ?? {}))
      toast.error(msg || 'Could not add variant')
    } finally {
      setVariantSaving(false)
    }
  }

  const handleAddComboComponent = async () => {
    if (!editId || !newCombo.component_product) {
      toast.error('Choose a component product')
      return
    }
    setComboSaving(true)
    try {
      const { data } = await inventoryApi.createComboComponent({
        combo_product: editId,
        component_product: newCombo.component_product,
        quantity: newCombo.quantity || '1',
      })
      setComboComponentsList((c) => [...c, data])
      setNewCombo({ component_product: '', quantity: '1' })
    } catch (err: any) {
      const apiErr = err?.response?.data?.error ?? err?.response?.data
      const msg = typeof apiErr === 'string' ? apiErr : (apiErr?.message ?? (Array.isArray(apiErr) ? apiErr.join(' ') : 'Could not add component'))
      toast.error(msg)
    } finally {
      setComboSaving(false)
    }
  }

  const handleDeleteComboComponent = async (id: string) => {
    const ok = await confirmDialog('Remove this component from the combo?')
    if (!ok) return
    setComboComponentsList((c) => c.filter((x) => x.id !== id))
    try {
      await inventoryApi.deleteComboComponent(id)
    } catch {
      toast.error('Could not remove component')
    }
  }

  // Custom fields are plain JSON on the product row (no separate endpoint),
  // so edits here are local until the main form is saved — unlike
  // variants/combo components, which write immediately.
  const addCustomFieldRow = () => {
    if (customFieldRows.length >= 5) {
      toast.error('A product can have at most 5 custom fields')
      return
    }
    setCustomFieldRows((rows) => [...rows, { label: '', value: '' }])
  }
  const updateCustomFieldRow = (idx: number, field: 'label' | 'value', v: string) => {
    setCustomFieldRows((rows) => rows.map((r, i) => (i === idx ? { ...r, [field]: v } : r)))
  }
  const removeCustomFieldRow = (idx: number) => {
    setCustomFieldRows((rows) => rows.filter((_, i) => i !== idx))
  }

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    // Strip empty optional numeric fields — DRF rejects '' for DecimalField/IntegerField
    const payload: Record<string, unknown> = {
      ...form,
      cost_price: stripCommas(form.cost_price),
      owner_cost_price: stripCommas(form.owner_cost_price) || '0',
      selling_price: stripCommas(form.selling_price),
      wholesale_price: stripCommas(form.wholesale_price) || '0',
      quantity_in_pack: form.quantity_in_pack || '1',
      is_active: form.is_active,
      description: form.description || '',
      barcode: form.barcode || '',
    }
    // Send category FK id (empty string → null so Django treats it as "no category")
    if (form.category) payload.category = form.category
    else payload.category = null
    if (!payload.alcohol_percentage) delete payload.alcohol_percentage
    if (!payload.volume_ml) delete payload.volume_ml
    if (!payload.max_stock_level) delete payload.max_stock_level
    // Send null for tax_class when empty, or when is_taxable is false
    if (!payload.is_taxable) payload.tax_class = null
    else if (!payload.tax_class) payload.tax_class = null
    // Blank GL override means "use the organisation default"
    if (!payload.inventory_account) payload.inventory_account = null
    if (!payload.sales_account) payload.sales_account = null
    if (!payload.cogs_account) payload.cogs_account = null
    if (!payload.wages_account) payload.wages_account = null
    if (!payload.parent_product) payload.parent_product = null
    payload.custom_fields = Object.fromEntries(
      customFieldRows.filter((r) => r.label.trim()).map((r) => [r.label.trim(), r.value]),
    )
    // Editing without detail hydration (offline): never send the fields the slim
    // list doesn't carry — sending their empty defaults would wipe real data.
    // (inventory_account was missing from this list too — same bug, fixed here
    // since the new GL fields share its exact "not in the slim list" shape.)
    if (editId && !editHydrated) {
      for (const k of [
        'description', 'barcode', 'wholesale_price', 'max_stock_level', 'quantity_in_pack',
        'inventory_account', 'sales_account', 'cogs_account', 'wages_account',
        'costing_method', 'tax_type', 'barcode_symbology',
        'parent_product', 'variant_attributes', 'custom_fields',
      ]) {
        delete payload[k]
      }
    }
    try {
      if (editId) {
        await inventoryApi.updateProduct(editId, payload)

        // Apply stock quantity change if user edited the qty field
        const newQty = parseFloat(editStockQty) || 0
        const delta = newQty - editOrigQty
        const targetWarehouse = editWarehouse || (warehouses.find((w: any) => w.is_default)?.id ?? warehouses[0]?.id)
        if (form.product_type === 'physical' && delta !== 0 && targetWarehouse) {
          try {
            await inventoryApi.adjustStock({
              product_id: editId,
              warehouse_id: targetWarehouse,
              quantity: delta,
              reason: delta > 0 ? 'Stock adjustment (added via product edit)' : 'Stock adjustment (removed via product edit)',
            })
          } catch {
            toast.error('Stock quantity could not be updated — adjust it from the Stock page')
          }
        }

        // Transfer stock if warehouse changed and there is stock to move
        if (
          form.product_type === 'physical' &&
          editWarehouse &&
          editOrigWarehouse &&
          editWarehouse !== editOrigWarehouse &&
          editOrigQty > 0
        ) {
          try {
            await inventoryApi.transferStock({
              product_id: editId,
              from_warehouse_id: editOrigWarehouse,
              to_warehouse_id: editWarehouse,
              quantity: editOrigQty,
              notes: 'Warehouse reassigned via product edit',
            })
            toast.success('Product updated and stock moved to new warehouse')
          } catch {
            toast.success('Product updated')
            toast.error('Stock transfer failed — move stock manually from the Stock page')
          }
        } else {
          toast.success('Product updated')
        }
      } else {
        const { data: newProduct } = await inventoryApi.createProduct(payload)
        // Set opening stock if a warehouse was selected (always register product in warehouse)
        const qty = parseFloat(batchForm.quantity) || 0
        if (batchForm.warehouse && form.product_type === 'physical') {
          if (batchForm.batch_number) {
            // Create a tracked Batch record (appears in Batches & Lots module)
            const batchPayload: Record<string, unknown> = {
              product: newProduct.id,
              warehouse: batchForm.warehouse,
              batch_number: batchForm.batch_number,
              quantity: qty,
              // Pull from main form — no need to re-enter these in batch details
              unit_cost: stripCommas(form.cost_price) || '0',
              qty_per_pack: form.quantity_in_pack || '1',
            }
            // DateInput always emits ISO YYYY-MM-DD — pass through directly
            if (batchForm.manufacture_date) batchPayload.manufacture_date = batchForm.manufacture_date
            if (batchForm.expiry_date) batchPayload.expiry_date = batchForm.expiry_date
            if (form.reorder_level) batchPayload.min_quantity = form.reorder_level
            if (form.max_stock_level) batchPayload.max_quantity = form.max_stock_level
            try {
              await inventoryApi.createBatch(batchPayload)
            } catch {
              toast.error('Batch could not be saved — add it from Batches & Lots page')
            }
            // Post the opening balance regardless of batch creation result so the
            // warehouse always has stock. Uses the GL-correct take-on path (Debit
            // Inventory / Credit Take-On Suspense), not a plain stock adjustment.
            if (qty > 0) {
              try {
                await inventoryApi.setProductOpeningBalance(newProduct.id, {
                  warehouse_id: batchForm.warehouse,
                  quantity: qty,
                  unit_cost: stripCommas(form.cost_price) || undefined,
                  as_of_date: batchForm.as_of_date || undefined,
                })
                toast.success('Product created with batch/lot')
              } catch {
                toast.error('Opening stock could not be saved — add it from Beginning Balances')
              }
            } else {
              toast.success('Product created with batch/lot')
            }
          } else {
            // Simple opening stock (no batch tracking)
            if (qty > 0) {
              try {
                await inventoryApi.setProductOpeningBalance(newProduct.id, {
                  warehouse_id: batchForm.warehouse,
                  quantity: qty,
                  unit_cost: stripCommas(form.cost_price) || undefined,
                  as_of_date: batchForm.as_of_date || undefined,
                })
                toast.success('Product created with opening stock')
              } catch {
                toast.error('Opening stock could not be saved — add it from Beginning Balances')
              }
            } else {
              toast.success('Product created')
            }
          }
        } else {
          toast.success('Product created')
        }
      }
      setShowModal(false)
      fetchProducts()
    } catch (err: any) {
      const apiErr = err?.response?.data?.error
      const msg = typeof apiErr === 'string' ? apiErr : (apiErr?.message ?? (editId ? 'Failed to update product' : 'Failed to create product'))
      toast.error(msg)
    } finally {
      setSaving(false)
    }
  }

  const handleRefresh = async () => {
    bypassNextGets()
    setRefreshing(true)
    await fetchProducts()
    setRefreshing(false)
  }

  const toggleSelect = (id: string) =>
    setSelectedIds((prev) => {
      const n = new Set(prev)
      if (n.has(id)) n.delete(id)
      else n.add(id)
      return n
    })

  const toggleSelectAll = () => {
    const pageIds = paged.map((p) => p.id)
    const allSelected = pageIds.every((id) => selectedIds.has(id))
    setSelectedIds((prev) => {
      const n = new Set(prev)
      if (allSelected) pageIds.forEach((id) => n.delete(id))
      else pageIds.forEach((id) => n.add(id))
      return n
    })
  }

  const handleBulkDelete = async () => {
    if (!(await confirmDialog(`Delete ${selectedIds.size} selected product(s)? This cannot be undone.\n\nProducts used on invoices or purchase orders will be skipped.`))) return
    setBulkDeleting(true)
    let deleted = 0, failed = 0
    for (const id of selectedIds) {
      try { await inventoryApi.deleteProduct(id); deleted++ } catch { failed++ }
    }
    const msg = failed
      ? `Deleted ${deleted}, ${failed} skipped (linked to documents)`
      : `Deleted ${deleted} product${deleted !== 1 ? 's' : ''}`
    toast.success(msg, { duration: 5000 })
    setSelectedIds(new Set())
    setBulkDeleting(false)
    bypassNextGets()
    fetchProducts()
  }

  const handleDelete = async (p: Product) => {
    if (!(await confirmDialog(`Delete "${p.name}"? This cannot be undone.\n\nStock levels and batch records for this product will be removed. Products that appear on invoices or purchase orders cannot be deleted.`))) return
    setDeletingId(p.id)
    try {
      await inventoryApi.deleteProduct(p.id)
      toast.success('Product deleted')
      bypassNextGets()
      fetchProducts()
    } catch (err: any) {
      const apiErr = err?.response?.data?.error
      const msg = typeof apiErr === 'string' ? apiErr : (apiErr?.message ?? 'Failed to delete product')
      toast.error(msg, { duration: 6000 })
    } finally {
      setDeletingId(null)
    }
  }

  const handleDeleteAll = async () => {
    setDeletingAll(true)
    try {
      const { data } = await inventoryApi.bulkDeleteProducts()
      if (data.skipped?.length) {
        toast.success(`Deleted ${data.deleted} product${data.deleted !== 1 ? 's' : ''}. ${data.skipped.length} skipped (used in documents).`, { duration: 7000 })
      } else {
        toast.success(`All ${data.deleted} product${data.deleted !== 1 ? 's' : ''} deleted.`)
      }
      setShowDeleteAll(false)
      bypassNextGets()  // force-refresh stock levels, batches, warehouses pages
      fetchProducts()
    } catch (err: any) {
      const apiErr = err?.response?.data?.error
      const msg = typeof apiErr === 'string' ? apiErr : (apiErr?.message ?? 'Failed to delete products')
      toast.error(msg, { duration: 6000 })
    } finally {
      setDeletingAll(false)
    }
  }

  const openHistory = async (p: Product) => {
    setHistoryProduct(p)
    setHistoryItems([])
    setHistoryDateFrom('')
    setHistoryDateTo('')
    setHistoryLoading(true)
    try {
      const { data } = await salesApi.productHistory(p.id)
      setHistoryItems(data.results ?? [])
    } catch {
      toast.error('Failed to load transaction history')
    } finally {
      setHistoryLoading(false)
    }
  }

  const applyHistoryDateFilter = async () => {
    if (!historyProduct) return
    setHistoryLoading(true)
    try {
      const params: { date_from?: string; date_to?: string } = {}
      if (historyDateFrom) params.date_from = historyDateFrom
      if (historyDateTo) params.date_to = historyDateTo
      const { data } = await salesApi.productHistory(historyProduct.id, params)
      setHistoryItems(data.results ?? [])
    } catch {
      toast.error('Failed to load transaction history')
    } finally {
      setHistoryLoading(false)
    }
  }

  const upd = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
    setForm((f) => ({ ...f, [k]: e.target.value }))

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Products</h1>
          <p className="text-slate-400 text-sm">{total} SKUs in catalogue</p>
        </div>
        <div className="flex items-center gap-2 sm:ml-auto">
          <button onClick={handleRefresh} disabled={refreshing} className="btn-ghost p-2 text-slate-400 hover:text-white" title="Refresh">
            <RefreshCw size={16} className={refreshing ? 'animate-spin' : ''} />
          </button>
          {products.length > 0 && (
            <>
              <div className="relative">
                <button
                  onClick={() => setExportOpen((v) => !v)}
                  className="btn-ghost flex items-center gap-1.5 px-3 py-2 text-sm text-slate-400 hover:text-white"
                  title="Export"
                >
                  <FileDown size={16} />
                  Export
                  <ChevronDown size={13} className={`transition-transform ${exportOpen ? 'rotate-180' : ''}`} />
                </button>
                {exportOpen && (
                  <div className="absolute right-0 top-full mt-1 z-30 bg-surface-800 border border-surface-700 rounded-xl shadow-2xl py-1 min-w-[140px]" onMouseLeave={() => setExportOpen(false)}>
                    <button
                      onClick={() => { setExportOpen(false); exportProductsPDF(products, organisation) }}
                      className="w-full flex items-center gap-2.5 px-4 py-2.5 text-sm text-slate-300 hover:bg-surface-700 hover:text-white transition-colors"
                    >
                      <FileDown size={14} className="text-slate-400" /> PDF
                    </button>
                    <button
                      onClick={() => { setExportOpen(false); exportProductsExcel(products) }}
                      className="w-full flex items-center gap-2.5 px-4 py-2.5 text-sm text-slate-300 hover:bg-surface-700 hover:text-white transition-colors"
                    >
                      <Table2 size={14} className="text-emerald-400" /> Excel (XLS)
                    </button>
                    <button
                      onClick={() => { setExportOpen(false); exportProductsCSV(products) }}
                      className="w-full flex items-center gap-2.5 px-4 py-2.5 text-sm text-slate-300 hover:bg-surface-700 hover:text-white transition-colors"
                    >
                      <ArrowDownCircle size={14} className="text-blue-400" /> CSV
                    </button>
                  </div>
                )}
              </div>
              <button onClick={() => setShowDeleteAll(true)} className="btn-ghost p-2 text-red-400 hover:text-red-300 hover:bg-red-500/10" title="Delete all products">
                <Trash2 size={16} />
              </button>
            </>
          )}
          <button onClick={openCreate} className="btn-primary">
            <Plus size={16} /> Add Product
          </button>
        </div>
      </div>

      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative max-w-sm">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
          <input className="input pl-9" placeholder="Search by name or SKU…" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <SortSelect
          value={sortBy}
          onChange={setSortBy}
          options={[
            { label: 'Name A→Z', value: 'name' },
            { label: 'Name Z→A', value: '-name' },
            { label: 'Newest first', value: '-created_at' },
            { label: 'Oldest first', value: 'created_at' },
            { label: 'Cost ↑', value: 'cost_price' },
            { label: 'Cost ↓', value: '-cost_price' },
            { label: 'Selling Price ↑', value: 'selling_price' },
            { label: 'Selling Price ↓', value: '-selling_price' },
          ]}
        />
      </div>

      {selectedIds.size > 0 && (
        <div className="flex items-center gap-3 bg-brand-500/10 border border-brand-500/30 rounded-xl px-4 py-3">
          <CheckSquare size={16} className="text-brand-400 shrink-0" />
          <span className="text-sm text-brand-300 font-medium">{selectedIds.size} product{selectedIds.size !== 1 ? 's' : ''} selected</span>
          <div className="ml-auto flex items-center gap-2">
            <button onClick={() => setSelectedIds(new Set())} className="btn-ghost px-3 py-1.5 text-xs text-slate-400">Clear</button>
            <button
              onClick={handleBulkDelete}
              disabled={bulkDeleting}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-red-400 bg-red-500/10 hover:bg-red-500/20 border border-red-500/30 rounded-lg transition-colors disabled:opacity-50"
            >
              {bulkDeleting ? <Loader2 size={13} className="animate-spin" /> : <Trash2 size={13} />}
              Delete Selected
            </button>
          </div>
        </div>
      )}

      <div className="card p-0 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-surface-700">
                <th className="pl-5 pr-2 py-3.5 w-8">
                  <input
                    type="checkbox"
                    className="accent-orange-500 w-4 h-4 cursor-pointer"
                    checked={paged.length > 0 && paged.every((p) => selectedIds.has(p.id))}
                    onChange={toggleSelectAll}
                  />
                </th>
                {['SKU', 'Product', 'Type', 'Cost Price', ...(showOwnerFeatures ? ['Owner Cost'] : []), 'Selling Price', 'Wholesale Price', 'Profit / Margin', 'Stock', 'Status', ''].map((h) => (
                  <th key={h} className={`px-5 py-3.5 text-left text-xs font-semibold uppercase tracking-wider ${h === 'Owner Cost' ? 'text-brand-400' : 'text-slate-400'}`}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                Array.from({ length: 5 }).map((_, i) => (
                  <tr key={i} className="table-row">
                    {Array.from({ length: 9 }).map((_, j) => (
                      <td key={j} className="px-5 py-3.5"><div className="h-4 bg-surface-700 rounded animate-pulse w-24" /></td>
                    ))}
                  </tr>
                ))
              ) : total === 0 ? (
                <tr><td colSpan={9} className="px-5 py-12 text-center">
                  <Package size={32} className="mx-auto mb-2 text-slate-600" />
                  <p className="text-slate-500">No products found</p>
                </td></tr>
              ) : (
                paged.map((p) => {
                  const cost = parseFloat(p.cost_price) || 0
                  const sell = parseFloat(p.selling_price) || 0
                  const profit = sell - cost
                  const margin = sell > 0 ? ((profit / sell) * 100).toFixed(1) : '0.0'
                  const isProfit = profit >= 0
                  return (
                  <tr key={p.id} className={`table-row ${selectedIds.has(p.id) ? 'bg-brand-500/5' : ''}`}>
                    <td className="pl-5 pr-2 py-3.5 w-8">
                      <input
                        type="checkbox"
                        className="accent-orange-500 w-4 h-4 cursor-pointer"
                        checked={selectedIds.has(p.id)}
                        onChange={() => toggleSelect(p.id)}
                      />
                    </td>
                    <td className="px-5 py-3.5 font-mono text-xs text-brand-400">{p.sku}</td>
                    <td className="px-5 py-3.5">
                      <p className="font-medium text-white">{p.name}</p>
                      {p.volume_ml && <p className="text-xs text-slate-500">{p.volume_ml}ml · {p.alcohol_percentage}% ABV</p>}
                    </td>
                    <td className="px-5 py-3.5">
                      {(p as any).product_type === 'service' ? <span className="badge-blue">Service</span>
                        : (p as any).product_type === 'digital' ? <span className="badge-orange">Digital</span>
                        : (p as any).product_type === 'variable' ? <span className="badge-purple">Variable</span>
                        : (p as any).product_type === 'combo' ? <span className="badge-green">Combo</span>
                        : <span className="badge-slate">Physical</span>}
                    </td>
                    <td className="px-5 py-3.5 text-slate-300">{formatCurrency(p.cost_price)}</td>
                    {showOwnerFeatures && (
                      <td className="px-5 py-3.5 font-mono text-brand-400 text-xs">{formatCurrency(p.owner_cost_price ?? '0')}</td>
                    )}
                    <td className="px-5 py-3.5 font-semibold text-white">{formatCurrency(p.selling_price)}</td>
                    <td className="px-5 py-3.5 text-slate-400">{(p as any).wholesale_price && parseFloat((p as any).wholesale_price) > 0 ? formatCurrency((p as any).wholesale_price) : <span className="text-slate-600">—</span>}</td>
                    <td className="px-5 py-3.5">
                      <div className="flex items-center gap-1.5">
                        {isProfit
                          ? <TrendingUp size={13} className="text-emerald-400 shrink-0" />
                          : <TrendingDown size={13} className="text-red-400 shrink-0" />}
                        <div>
                          <p className={`text-sm font-semibold ${isProfit ? 'text-emerald-400' : 'text-red-400'}`}>
                            {formatCurrency(profit.toFixed(2))}
                          </p>
                          <p className="text-xs text-slate-500">{margin}% margin</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-5 py-3.5">
                      {['service', 'digital', 'variable', 'combo'].includes((p as any).product_type) ? (
                        <span className="badge-slate">N/A</span>
                      ) : (
                        <div className="flex flex-col gap-1">
                          <span className={p.total_stock <= p.reorder_level ? 'badge-red' : 'badge-green'}>
                            {p.total_stock <= p.reorder_level && <AlertTriangle size={11} />}
                            {p.total_stock} units
                          </span>
                          {(p as any).quantity_incoming > 0 && (
                            <span className="badge-blue flex items-center gap-1 w-fit">
                              <ArrowDownCircle size={11} />
                              +{(p as any).quantity_incoming} incoming
                            </span>
                          )}
                        </div>
                      )}
                    </td>
                    <td className="px-5 py-3.5">
                      <div className="flex flex-col gap-1">
                        <span className={p.is_active ? 'badge-green' : 'badge-slate'}>
                          {p.is_active ? 'Active' : 'Inactive'}
                        </span>
                        {p.is_taxable && <span className="badge-orange text-[10px]">VAT</span>}
                      </div>
                    </td>
                    <td className="px-5 py-3.5">
                      <div className="flex items-center gap-1">
                        <button onClick={() => openEdit(p)} className="btn-ghost p-1.5 text-slate-400 hover:text-white" title="Edit">
                          <Pencil size={14} />
                        </button>
                        <button onClick={() => openHistory(p)} className="btn-ghost p-1.5 text-slate-400 hover:text-brand-400" title="Transaction History">
                          <History size={14} />
                        </button>
                        {canEdit && (
                          <button
                            onClick={() => handleDelete(p)}
                            disabled={deletingId === p.id}
                            className="btn-ghost p-1.5 text-slate-400 hover:text-red-400"
                            title="Delete product"
                          >
                            {deletingId === p.id ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />}
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
        <Pagination page={page} totalPages={totalPages} pageSize={pageSize} total={total}
          onPage={setPage} onPageSize={setPageSize} />
      </div>

      {/* Create / Edit Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
          <div className="bg-surface-800 border border-surface-700 rounded-2xl w-full max-w-lg shadow-2xl animate-slide-up max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b border-surface-700">
              <h2 className="font-semibold text-white text-lg">{editId ? 'Edit Product' : 'New Product'}</h2>
              <button onClick={() => setShowModal(false)} className="btn-ghost p-1.5"><X size={18} /></button>
            </div>
            <form onSubmit={handleSave} className="p-6 space-y-4">
              {/* Product Type */}
              <div>
                <label className="label">Product Type * <FieldTooltip text="Physical = items you can touch and stock (clothing, drinks, electronics). Service = things you do for customers (repairs, consultations). Digital = files or downloads. This affects how stock is tracked." /></label>
                <select className="input" value={form.product_type} onChange={upd('product_type')}>
                  {PRODUCT_TYPES.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">SKU * <FieldTooltip text="Stock Keeping Unit — a unique code you create for this product. E.g. 'COKE-50CL' or 'SHIRT-RED-L'. Makes searching and reporting easier." /></label>
                  <input className="input" value={form.sku} onChange={upd('sku')} required placeholder="SVC-001" />
                </div>
                <div>
                  <label className="label">Unit <FieldTooltip text="How this product is counted or sold. Choose 'piece' for individual items, 'carton' for boxes, 'kg' for weight-based products, 'dozen' for groups of 12, etc." /></label>
                  <select className="input" value={form.unit_of_measure} onChange={upd('unit_of_measure')}>
                    {UNITS_OF_MEASURE.map((u) => <option key={u} value={u}>{u}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="label">Product / Service Name * <FieldTooltip text="The name that will appear on invoices, receipts, and reports. Use a clear, descriptive name your customers will recognise." /></label>
                <input className="input" value={form.name} onChange={upd('name')} required placeholder="e.g. Consulting, Delivery, Software License" />
              </div>
              <div>
                <label className="label">Description</label>
                <input className="input" value={(form as any).description ?? ''} onChange={upd('description')} placeholder="Optional short description" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">Category</label>
                  <select className="input" value={(form as any).category ?? ''} onChange={upd('category')}>
                    <option value="">— No category —</option>
                    {categories.map((c) => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="label">Barcode <FieldTooltip text="Leave blank to auto-generate one when you create the product. Enter a value here only if this item already has a printed barcode." /></label>
                  <input className="input" value={(form as any).barcode ?? ''} onChange={upd('barcode')} placeholder={editId ? 'Optional' : 'Auto-generated if left blank'} />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">Barcode Symbology</label>
                  <select className="input" value={(form as any).barcode_symbology ?? 'code128'} onChange={upd('barcode_symbology')}>
                    {BARCODE_SYMBOLOGIES.map((s) => (
                      <option key={s.value} value={s.value}>{s.label}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                <p className="text-sm font-semibold text-white">Product Images</p>
                {!editId ? (
                  <p className="text-xs text-slate-500">Save the product first, then add photos.</p>
                ) : !editHydrated ? (
                  <p className="text-xs text-slate-500">Loading…</p>
                ) : (
                  <>
                    <label className={`flex flex-col items-center justify-center gap-1.5 border-2 border-dashed rounded-xl py-6 transition-colors ${galleryUploading ? 'border-surface-700 cursor-wait' : 'border-surface-600 hover:border-brand-500 cursor-pointer'}`}>
                      {galleryUploading ? <Loader2 size={20} className="text-slate-400 animate-spin" /> : <Upload size={20} className="text-slate-400" />}
                      <span className="text-sm text-slate-300">{galleryUploading ? 'Uploading…' : 'Add images'}</span>
                      <span className="text-[11px] text-slate-500">Supported formats: JPG, PNG, GIF</span>
                      <input
                        type="file"
                        accept="image/png,image/jpeg,image/gif,image/webp"
                        multiple
                        className="hidden"
                        disabled={galleryUploading}
                        onChange={(e) => { handleImageFilesSelected(e.target.files); e.target.value = '' }}
                      />
                    </label>
                    {galleryImages.length === 0 ? (
                      <p className="text-xs text-slate-500 text-center py-2">No images yet. Add photos using the area above.</p>
                    ) : (
                      <>
                        <div className="grid grid-cols-4 gap-3">
                          {galleryImages.map((img) => (
                            <div
                              key={img.id}
                              draggable
                              onDragStart={() => setDragImageId(img.id)}
                              onDragOver={(e) => e.preventDefault()}
                              onDrop={() => handleImageDrop(img.id)}
                              onClick={() => handleSetMainImage(img.id)}
                              title={img.is_main ? 'Cover photo' : 'Click to set as cover photo — drag to reorder'}
                              className={`relative group aspect-square rounded-lg overflow-hidden border-2 cursor-pointer ${img.is_main ? 'border-brand-500' : 'border-surface-700'}`}
                            >
                              <img src={img.image} alt="" className="w-full h-full object-cover" />
                              {img.is_main && (
                                <span className="absolute top-1 left-1 badge-blue text-[9px] px-1.5 py-0.5">Cover</span>
                              )}
                              <button
                                type="button"
                                onClick={(e) => { e.stopPropagation(); handleDeleteImage(img.id) }}
                                className="absolute top-1 right-1 bg-black/60 hover:bg-red-600 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                              >
                                <X size={12} />
                              </button>
                            </div>
                          ))}
                        </div>
                        <p className="text-[11px] text-slate-500">Click a thumbnail to set the main image. Drag to reorder.</p>
                      </>
                    )}
                  </>
                )}
              </div>

              {form.product_type === 'variable' && (
                <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                  <p className="text-sm font-semibold text-white">Variants</p>
                  {!editId ? (
                    <p className="text-xs text-slate-500">Save this Variable Product first, then add its variants.</p>
                  ) : !editHydrated ? (
                    <p className="text-xs text-slate-500">Loading…</p>
                  ) : (
                    <>
                      {variantList.length === 0 ? (
                        <p className="text-xs text-slate-500">No variants yet. Add one below — e.g. "Size: Large, Color: Red".</p>
                      ) : (
                        <div className="space-y-1.5">
                          {variantList.map((v) => (
                            <div key={v.id} className="flex items-center justify-between text-sm bg-surface-900/50 rounded-lg px-3 py-2">
                              <div>
                                <span className="text-white font-medium">{v.sku}</span>
                                <span className="text-slate-400 ml-2">{v.name}</span>
                                {Object.keys(v.variant_attributes ?? {}).length > 0 && (
                                  <span className="text-[11px] text-slate-500 ml-2">
                                    ({Object.entries(v.variant_attributes).map(([k, val]) => `${k}: ${val}`).join(', ')})
                                  </span>
                                )}
                              </div>
                              <span className="text-slate-400 text-xs">Stock: {v.total_stock}</span>
                            </div>
                          ))}
                        </div>
                      )}
                      <div className="grid grid-cols-2 gap-2 pt-2 border-t border-surface-700/60">
                        <input className="input" placeholder="Variant SKU" value={newVariant.sku}
                          onChange={(e) => setNewVariant((n) => ({ ...n, sku: e.target.value }))} />
                        <input className="input" placeholder="Variant Name" value={newVariant.name}
                          onChange={(e) => setNewVariant((n) => ({ ...n, name: e.target.value }))} />
                        <input className="input col-span-2" placeholder="Attributes (e.g. Size: Large, Color: Red)" value={newVariant.attributes}
                          onChange={(e) => setNewVariant((n) => ({ ...n, attributes: e.target.value }))} />
                        <input className="input" type="number" min="0" placeholder="Cost Price" value={newVariant.cost_price}
                          onChange={(e) => setNewVariant((n) => ({ ...n, cost_price: e.target.value }))} />
                        <input className="input" type="number" min="0" placeholder="Selling Price" value={newVariant.selling_price}
                          onChange={(e) => setNewVariant((n) => ({ ...n, selling_price: e.target.value }))} />
                      </div>
                      <button type="button" className="btn-secondary w-full text-sm" disabled={variantSaving} onClick={handleAddVariant}>
                        {variantSaving ? <Loader2 size={14} className="animate-spin mx-auto" /> : 'Add Variant'}
                      </button>
                    </>
                  )}
                </div>
              )}

              {form.product_type === 'combo' && (
                <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                  <p className="text-sm font-semibold text-white">Combo Components</p>
                  {!editId ? (
                    <p className="text-xs text-slate-500">Save this Combo Product first, then add its components.</p>
                  ) : !editHydrated ? (
                    <p className="text-xs text-slate-500">Loading…</p>
                  ) : (
                    <>
                      {comboComponentsList.length === 0 ? (
                        <p className="text-xs text-slate-500">No components yet. Selling this combo will fail until at least one is added.</p>
                      ) : (
                        <div className="space-y-1.5">
                          {comboComponentsList.map((c) => (
                            <div key={c.id} className="flex items-center justify-between text-sm bg-surface-900/50 rounded-lg px-3 py-2">
                              <span className="text-white">{c.quantity} × {c.component_product_sku} — {c.component_product_name}</span>
                              <button type="button" onClick={() => handleDeleteComboComponent(c.id)} className="text-slate-400 hover:text-red-400">
                                <X size={14} />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                      <div className="grid grid-cols-3 gap-2 pt-2 border-t border-surface-700/60">
                        <select className="input col-span-2" value={newCombo.component_product}
                          onChange={(e) => setNewCombo((n) => ({ ...n, component_product: e.target.value }))}>
                          <option value="">— Choose component —</option>
                          {comboPickableProducts.filter((p) => p.id !== editId).map((p) => (
                            <option key={p.id} value={p.id}>{p.sku} — {p.name}</option>
                          ))}
                        </select>
                        <input className="input" type="number" min="0.01" step="0.01" placeholder="Qty" value={newCombo.quantity}
                          onChange={(e) => setNewCombo((n) => ({ ...n, quantity: e.target.value }))} />
                      </div>
                      <button type="button" className="btn-secondary w-full text-sm" disabled={comboSaving} onClick={handleAddComboComponent}>
                        {comboSaving ? <Loader2 size={14} className="animate-spin mx-auto" /> : 'Add Component'}
                      </button>
                    </>
                  )}
                </div>
              )}

              <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                <p className="text-sm font-semibold text-white">Custom Fields <FieldTooltip text="Add up to 5 of your own label/value pairs — e.g. Warranty, Material, Country of Origin." /></p>
                {editId && !editHydrated ? (
                  <p className="text-xs text-slate-500">Loading…</p>
                ) : (
                  <>
                    {customFieldRows.length === 0 ? (
                      <p className="text-xs text-slate-500">No custom fields yet.</p>
                    ) : (
                      <div className="space-y-2">
                        {customFieldRows.map((row, idx) => (
                          <div key={idx} className="flex items-center gap-2">
                            <input
                              className="input flex-1" placeholder="Label (e.g. Warranty)"
                              value={row.label} onChange={(e) => updateCustomFieldRow(idx, 'label', e.target.value)}
                            />
                            <input
                              className="input flex-1" placeholder="Value (e.g. 12 months)"
                              value={row.value} onChange={(e) => updateCustomFieldRow(idx, 'value', e.target.value)}
                            />
                            <button type="button" onClick={() => removeCustomFieldRow(idx)} className="text-slate-400 hover:text-red-400 shrink-0">
                              <X size={14} />
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                    {customFieldRows.length < 5 && (
                      <button type="button" onClick={addCustomFieldRow} className="btn-secondary w-full text-sm">
                        + Add Field
                      </button>
                    )}
                  </>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">Brand / Vendor <FieldTooltip text="The brand name or the company that makes or supplies this product. Optional — useful for filtering and reports." /></label>
                  <input className="input" value={form.brand} onChange={upd('brand')} placeholder="Optional" />
                </div>
                {form.product_type === 'physical' && (
                  <div>
                    <label className="label">Qty in Pack <FieldTooltip text="Number of individual units inside one pack or carton. E.g. '12' means a carton holds 12 bottles." /></label>
                    <input type="number" min="1" className="input" value={form.quantity_in_pack} onChange={upd('quantity_in_pack')} placeholder="1" />
                  </div>
                )}
              </div>
              {form.product_type === 'physical' && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="label">Min Safety Level <FieldTooltip text="Alert when stock drops below this quantity." /></label>
                    <input type="number" min="0" className="input" value={form.reorder_level} onChange={upd('reorder_level')} />
                  </div>
                  <div>
                    <label className="label">Max Safety Level <FieldTooltip text="Do not stock above this quantity. Leave blank for no limit." /></label>
                    <input type="number" min="0" className="input" value={form.max_stock_level} onChange={upd('max_stock_level')} placeholder="No limit" />
                  </div>
                </div>
              )}
              {editId && form.product_type === 'physical' && warehouses.length > 0 && (
                <div>
                  <label className="label">Warehouse <FieldTooltip text="Where this product is stocked. Changing this will transfer all existing stock to the selected warehouse." /></label>
                  <select className="input" value={editWarehouse} onChange={(e) => setEditWarehouse(e.target.value)}>
                    <option value="">— No warehouse assigned —</option>
                    {warehouses.map((w) => (
                      <option key={w.id} value={w.id}>{w.name}</option>
                    ))}
                  </select>
                  {editWarehouse && editOrigWarehouse && editWarehouse !== editOrigWarehouse && editOrigQty > 0 && (
                    <p className="text-xs text-amber-400 mt-1">{editOrigQty} units will be transferred to the new warehouse on save.</p>
                  )}
                </div>
              )}
              {editId && form.product_type === 'physical' && editStockQty !== '' && (
                <div>
                  <label className="label">
                    Stock Quantity
                    <FieldTooltip text="Current units on hand. Changing this value creates a stock adjustment movement immediately on save." />
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="1"
                    className="input"
                    value={editStockQty}
                    onChange={(e) => setEditStockQty(e.target.value)}
                  />
                  {(() => {
                    const delta = (parseFloat(editStockQty) || 0) - editOrigQty
                    if (delta === 0) return null
                    return (
                      <p className={`text-xs mt-1 ${delta > 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                        {delta > 0 ? `+${delta}` : delta} units will be {delta > 0 ? 'added' : 'removed'} on save
                      </p>
                    )
                  })()}
                </div>
              )}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">Cost Price * <FieldTooltip text="What you paid to buy or produce each unit. Used to calculate your profit margin. Never shown to customers." /></label>
                  <AmountInput className="input" value={form.cost_price} onChange={(v) => setForm((f) => ({ ...f, cost_price: v }))} required placeholder="5,500.00" />
                </div>
                <div>
                  <label className="label">Selling Price * <FieldTooltip text="The price you charge customers. This is what appears on invoices. Should always be higher than your cost price to make a profit." /></label>
                  <AmountInput className="input" value={form.selling_price} onChange={(v) => setForm((f) => ({ ...f, selling_price: v }))} required placeholder="8,500.00" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">Wholesale Price <FieldTooltip text="Discounted price for bulk / wholesale buyers." /></label>
                  <AmountInput className="input" value={form.wholesale_price} onChange={(v) => setForm((f) => ({ ...f, wholesale_price: v }))} placeholder="Optional" />
                </div>
              </div>
              {showOwnerFeatures && (
                <div className="p-3 rounded-xl border border-brand-500/20 bg-brand-500/5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <ShieldCheck size={13} className="text-brand-400" />
                    <label className="text-xs font-semibold text-brand-400 uppercase tracking-wide">Owner Cost Price</label>
                  </div>
                  <AmountInput
                    className="input"
                    value={form.owner_cost_price}
                    onChange={(v) => setForm((f) => ({ ...f, owner_cost_price: v }))}
                    placeholder="Your actual purchase cost (private)"
                  />
                  <p className="text-xs text-slate-500 mt-1.5">Only visible to you (owner). Used in owner profit analytics.</p>
                </div>
              )}
              {/* Physical-only fields */}
              {form.product_type === 'physical' && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="label">Volume (ml)</label>
                    <input type="number" className="input" value={form.volume_ml} onChange={upd('volume_ml')} placeholder="750" />
                  </div>
                  <div>
                    <label className="label">ABV (%)</label>
                    <input type="number" step="0.1" className="input" value={form.alcohol_percentage} onChange={upd('alcohol_percentage')} placeholder="40.0" />
                  </div>
                </div>
              )}
              {/* Active status + VAT / Tax */}
              <div className="border-t border-surface-700 pt-4 space-y-3">
                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={form.is_active}
                    onChange={(e) => setForm((f) => ({ ...f, is_active: e.target.checked }))}
                    className="w-4 h-4 accent-orange-500"
                  />
                  <span className="text-sm text-slate-300">Active <span className="text-slate-500">(uncheck to deactivate / hide from sales)</span></span>
                </label>
                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={form.is_taxable}
                    onChange={(e) => setForm((f) => ({ ...f, is_taxable: e.target.checked, tax_class: e.target.checked ? f.tax_class : '' }))}
                    className="w-4 h-4 accent-orange-500"
                  />
                  <span className="text-sm text-slate-300">Taxable (apply VAT on sales)</span>
                </label>
                {form.is_taxable && (
                  <div>
                    <label className="label">VAT Class</label>
                    <select
                      className="input"
                      value={form.tax_class}
                      onChange={upd('tax_class')}
                    >
                      <option value="">— No VAT class —</option>
                      {taxClasses.map((tc) => (
                        <option key={tc.id} value={tc.id}>
                          {tc.name} ({parseFloat(tc.rate).toFixed(1)}%)
                        </option>
                      ))}
                    </select>
                    {taxClasses.length === 0 && (
                      <p className="text-xs text-slate-500 mt-1">
                        No VAT classes configured. Add them in Tax → VAT Classes.
                      </p>
                    )}
                  </div>
                )}
                {form.is_taxable && (
                  <div>
                    <label className="label">Tax Type <FieldTooltip text="Exclusive: VAT is added on top of the price you set. Inclusive: the price you set already contains VAT, so it's backed out instead of added." /></label>
                    <select className="input" value={form.tax_type} onChange={upd('tax_type')}>
                      {TAX_TYPES.map((t) => (
                        <option key={t.value} value={t.value}>{t.label}</option>
                      ))}
                    </select>
                  </div>
                )}
              </div>

              {form.product_type === 'physical' && (
                <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                  <p className="text-sm font-semibold text-white">Inventory GL Mapped</p>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="label">Sales Account</label>
                      <GLAccountSelect value={form.sales_account}
                        onChange={(v) => setForm((f) => ({ ...f, sales_account: v }))} />
                    </div>
                    <div>
                      <label className="label">Inventory Account</label>
                      <GLAccountSelect value={form.inventory_account}
                        onChange={(v) => setForm((f) => ({ ...f, inventory_account: v }))} />
                    </div>
                  </div>
                  <div>
                    <label className="label">Cost of Sales Account</label>
                    <GLAccountSelect value={form.cogs_account}
                      onChange={(v) => setForm((f) => ({ ...f, cogs_account: v }))} />
                  </div>
                  <div>
                    <label className="label">Cost Method <FieldTooltip text="How this item's cost of goods sold is worked out when it sells. FIFO uses your oldest stock first, LIFO your newest, Average blends every purchase, and Specific Unit costs the exact batch you pick on the sale." /></label>
                    <select className="input" value={form.costing_method} onChange={upd('costing_method')}>
                      {COSTING_METHODS.map((m) => (
                        <option key={m.value} value={m.value}>{m.label}</option>
                      ))}
                    </select>
                  </div>
                  <p className="text-[11px] text-slate-500">
                    GL accounts this item's sales, stock value and cost of sales post to. Leave on the organisation default unless this item needs its own mapping.
                  </p>
                </div>
              )}

              {form.product_type === 'service' && (
                <div className="rounded-xl border border-surface-700/60 p-4 space-y-3">
                  <p className="text-sm font-semibold text-white">Service GL Mapped</p>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="label">Sales Account</label>
                      <GLAccountSelect value={form.sales_account}
                        onChange={(v) => setForm((f) => ({ ...f, sales_account: v }))} />
                    </div>
                    <div>
                      <label className="label">Salary / Wages Account</label>
                      <GLAccountSelect value={form.wages_account}
                        onChange={(v) => setForm((f) => ({ ...f, wages_account: v }))} />
                    </div>
                  </div>
                  <div>
                    <label className="label">Cost of Sales Account</label>
                    <GLAccountSelect value={form.cogs_account}
                      onChange={(v) => setForm((f) => ({ ...f, cogs_account: v }))} />
                  </div>
                  <p className="text-[11px] text-slate-500">
                    GL accounts this service's sales and cost post to. When Salary/Wages Account is set, a sale debits it instead of Cost of Sales.
                  </p>
                </div>
              )}

              {/* Opening stock / Batch (create only, physical only) */}
              {!editId && form.product_type === 'physical' && (
                <div className="rounded-xl border border-brand-500/30 bg-brand-500/5 p-4 space-y-3">
                  <div className="flex items-center gap-2">
                    <Package size={15} className="text-brand-400" />
                    <p className="text-sm font-semibold text-white">Available Quantity (Opening Stock)</p>
                  </div>
                  <p className="text-xs text-slate-400 -mt-1">Enter how many units you currently have. This immediately sets your stock level.</p>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="label">Quantity in Stock <FieldTooltip text="How many units you currently have. Leave at 0 to add stock later." /></label>
                      <input
                        type="number"
                        className="input"
                        placeholder="0"
                        min="0"
                        value={batchForm.quantity}
                        onChange={(e) => setBatchForm((b) => ({ ...b, quantity: e.target.value }))}
                      />
                    </div>
                    <div>
                      <label className="label">Location <FieldTooltip text="Which warehouse or store location holds this stock." /></label>
                      <select
                        className="input"
                        value={batchForm.warehouse}
                        onChange={(e) => setBatchForm((b) => ({ ...b, warehouse: e.target.value }))}
                      >
                        <option value="">— Select location —</option>
                        {warehouses.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}
                      </select>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="label">Balance As At <FieldTooltip text="The date this opening balance is effective from. Posts a take-on journal (Debit Inventory / Credit Take-On Suspense) as of this date." /></label>
                      <DateInput
                        value={batchForm.as_of_date}
                        onChange={(v) => setBatchForm((b) => ({ ...b, as_of_date: v }))}
                        placeholder="DD/MM/YYYY"
                      />
                    </div>
                  </div>
                  {/* Batch / Lot details — optional; if batch number provided, creates a tracked batch */}
                  <div>
                    <label className="label">Batch / Lot Number <span className="text-slate-500 font-normal">(optional)</span> <FieldTooltip text="Optional. Enter to create a tracked batch that appears in Batches & Lots. Leave blank for simple opening stock." /></label>
                    <input
                      type="text"
                      className="input"
                      placeholder="e.g. LOT-2026-001 (optional)"
                      value={batchForm.batch_number}
                      onChange={(e) => setBatchForm((b) => ({ ...b, batch_number: e.target.value }))}
                    />
                  </div>
                  {batchForm.batch_number && (
                    <div className="space-y-3 border border-surface-700/60 rounded-xl p-3">
                      <p className="text-xs text-slate-400">Batch details — cost price, qty per pack and stock limits are taken from the fields above</p>
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="label">Manufacture Date</label>
                          <DateInput
                            value={batchForm.manufacture_date}
                            onChange={(v) => setBatchForm((b) => ({ ...b, manufacture_date: v }))}
                            placeholder="DD/MM/YYYY"
                          />
                        </div>
                        <div>
                          <label className="label">Expiry Date</label>
                          <DateInput
                            value={batchForm.expiry_date}
                            onChange={(v) => setBatchForm((b) => ({ ...b, expiry_date: v }))}
                            placeholder="DD/MM/YYYY"
                          />
                        </div>
                      </div>
                    </div>
                  )}
                  {parseFloat(batchForm.quantity) > 0 && !batchForm.warehouse && (
                    <p className="text-xs text-amber-400">Select a location to save the opening stock.</p>
                  )}
                </div>
              )}

              <div className="flex gap-3 pt-2">
                <button type="button" onClick={() => setShowModal(false)} className="btn-secondary flex-1 justify-center">Cancel</button>
                <button type="submit" disabled={saving} className="btn-primary flex-1 justify-center">
                  {saving ? <Loader2 size={16} className="animate-spin" /> : (editId ? 'Save Changes' : 'Create Product')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Transaction History Modal */}
      {historyProduct && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
          <div className={`bg-surface-800 border border-surface-700 rounded-2xl w-full shadow-2xl animate-slide-up flex flex-col ${historyFullscreen ? 'max-w-full max-h-full h-full' : 'max-w-5xl max-h-[90vh]'}`}>
            <div className="flex items-center justify-between p-5 border-b border-surface-700 shrink-0">
              <div>
                <h2 className="font-semibold text-white text-lg">Transaction History</h2>
                <p className="text-xs text-slate-400 mt-0.5">{historyProduct.name} · {historyProduct.sku}</p>
              </div>
              <div className="flex items-center gap-2">
                <SortSelect
                  value={historySort}
                  onChange={setHistorySort}
                  options={[
                    { label: 'Newest first', value: '-issue_date' },
                    { label: 'Oldest first', value: 'issue_date' },
                    { label: 'Amount ↓', value: '-line_total' },
                    { label: 'Amount ↑', value: 'line_total' },
                    { label: 'Qty ↓', value: '-quantity' },
                    { label: 'Qty ↑', value: 'quantity' },
                  ]}
                />
                {historyItems.length > 0 && (
                  <>
                    <button
                      onClick={() => exportHistoryPDF(historyItems, historyProduct, organisation)}
                      className="btn-ghost p-1.5 text-xs flex items-center gap-1"
                      title="Export PDF"
                    >
                      <FileDown size={15} /> PDF
                    </button>
                    <button
                      onClick={() => exportHistoryCSV(historyItems, historyProduct)}
                      className="btn-ghost p-1.5 text-xs flex items-center gap-1"
                      title="Export Excel/CSV"
                    >
                      <Table2 size={15} /> Excel
                    </button>
                  </>
                )}
                <button onClick={() => setHistoryFullscreen(f => !f)} className="btn-ghost p-1.5" title={historyFullscreen ? 'Exit fullscreen' : 'Fullscreen'}>
                  {historyFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
                </button>
                <button onClick={() => { setHistoryProduct(null); setHistorySearch(''); setHistoryFullscreen(false); setHistoryDateFrom(''); setHistoryDateTo('') }} className="btn-ghost p-1.5"><X size={18} /></button>
              </div>
            </div>
            {/* Search + date filter bar */}
            <div className="px-5 py-3 border-b border-surface-700 shrink-0 flex flex-col sm:flex-row gap-2">
              <div className="relative flex-1">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
                <input
                  type="text"
                  placeholder="Search by date, reference, customer, sold by..."
                  value={historySearch}
                  onChange={e => setHistorySearch(e.target.value)}
                  className="input pl-8 py-1.5 text-sm w-full"
                />
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <DateInput value={historyDateFrom} onChange={setHistoryDateFrom} placeholder="From" className="input py-1.5 text-sm w-32" />
                <DateInput value={historyDateTo} onChange={setHistoryDateTo} placeholder="To" className="input py-1.5 text-sm w-32" />
                <button
                  onClick={applyHistoryDateFilter}
                  disabled={historyLoading}
                  className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium transition-colors disabled:opacity-50"
                >
                  Filter
                </button>
                {(historyDateFrom || historyDateTo) && (
                  <button
                    onClick={() => { setHistoryDateFrom(''); setHistoryDateTo(''); openHistory(historyProduct!) }}
                    className="px-2 py-1.5 rounded-lg text-slate-400 hover:text-white text-xs transition-colors"
                    title="Clear date filter"
                  >
                    <X size={14} />
                  </button>
                )}
              </div>
            </div>
            <div className="overflow-auto flex-1">
              {historyLoading ? (
                <div className="py-16 text-center"><Loader2 size={24} className="animate-spin mx-auto text-brand-400" /></div>
              ) : historyItems.length === 0 ? (
                <div className="py-16 text-center">
                  <History size={32} className="mx-auto mb-2 text-slate-600" />
                  <p className="text-slate-500">No transactions recorded for this product</p>
                </div>
              ) : (
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-surface-700">
                      {['Reference', 'Date', 'Customer', 'Sold By', 'Location', 'Payment', 'Qty', 'Unit Price', 'Total', 'Status'].map((h) => (
                        <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {[...historyItems].filter(item => {
                      if (!historySearch) return true
                      const q = historySearch.toLowerCase()
                      return (
                        item.invoice_number.toLowerCase().includes(q) ||
                        item.issue_date.includes(q) ||
                        (item.customer_name ?? '').toLowerCase().includes(q) ||
                        (item.sold_by ?? '').toLowerCase().includes(q)
                      )
                    }).sort((a, b) => {
                      const asc = !historySort.startsWith('-')
                      const field = historySort.replace(/^-/, '')
                      let av: number | string = 0, bv: number | string = 0
                      if (field === 'issue_date') { av = a.issue_date; bv = b.issue_date }
                      else if (field === 'line_total') { av = parseFloat(a.line_total); bv = parseFloat(b.line_total) }
                      else if (field === 'quantity') { av = parseFloat(a.quantity); bv = parseFloat(b.quantity) }
                      if (av < bv) return asc ? -1 : 1
                      if (av > bv) return asc ? 1 : -1
                      return 0
                    }).map((item, idx) => (
                      <tr key={idx} className={`table-row ${item.status === 'opening' ? 'bg-brand-500/5' : ''}`}>
                        <td className="px-4 py-3 font-mono text-xs text-brand-400">{item.invoice_number}</td>
                        <td className="px-4 py-3 text-slate-300 whitespace-nowrap">{formatDate(item.issue_date)}</td>
                        <td className="px-4 py-3 text-white">{item.customer_name}</td>
                        <td className="px-4 py-3 text-slate-300">{item.sold_by}</td>
                        <td className="px-4 py-3 text-slate-300">{item.warehouse}</td>
                        <td className="px-4 py-3 capitalize text-slate-300">{item.payment_method.replace('_', ' ')}</td>
                        <td className="px-4 py-3 text-white font-medium">{item.quantity}</td>
                        <td className="px-4 py-3 text-slate-300">{formatCurrency(item.unit_price)}</td>
                        <td className="px-4 py-3 font-semibold text-white">{formatCurrency(item.line_total)}</td>
                        <td className="px-4 py-3">
                          <span className={`badge-${item.status === 'paid' ? 'green' : item.status === 'voided' ? 'red' : item.status === 'opening' ? 'blue' : 'slate'}`}>
                            {item.status === 'opening' ? 'opening balance' : item.status}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      )}

      {showDeleteAll && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-surface-800 border border-red-500/30 rounded-xl p-6 max-w-sm w-full shadow-2xl">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-red-500/10 rounded-lg">
                <Trash2 size={20} className="text-red-400" />
              </div>
              <h2 className="text-lg font-semibold text-white">Delete All Products</h2>
            </div>
            <p className="text-slate-300 text-sm mb-2">
              This will permanently delete <span className="text-white font-semibold">{products.length} product{products.length !== 1 ? 's' : ''}</span> from your catalogue.
            </p>
            <p className="text-slate-400 text-xs mb-6">
              Products used in invoices, purchase orders, or returns will be skipped. Stock records and batch data will be removed. This cannot be undone.
            </p>
            <div className="flex gap-3">
              <button onClick={() => setShowDeleteAll(false)} disabled={deletingAll} className="flex-1 btn-ghost">
                Cancel
              </button>
              <button onClick={handleDeleteAll} disabled={deletingAll} className="flex-1 bg-red-600 hover:bg-red-700 text-white rounded-lg px-4 py-2 text-sm font-medium flex items-center justify-center gap-2 transition-colors">
                {deletingAll ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />}
                {deletingAll ? 'Deleting…' : 'Delete All'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
