# Generated by Django 5.1.4 on 2026-03-12 12:33

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_penalty_loan'),
        ('tenancy', '0007_letterhead_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepenalty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='amount_repaid',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='monthly_installment',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='principal_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='total_repayable',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='loan_deductions',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='penalty_deductions',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
