# Generated by Django 5.1.4 on 2026-03-12 13:01

import apps.payroll.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeeloan_deleted_at_employeepenalty_deleted_at_and_more'),
        ('tenancy', '0007_letterhead_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('cv', 'CV / Resume'), ('id', 'ID Card / Passport'), ('certificate', 'Certificate / Qualification'), ('contract', 'Employment Contract'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=apps.payroll.models._employee_doc_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['document_type', 'name'],
            },
        ),
    ]
