# Generated by Django 5.1.4 on 2026-03-25 21:48

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employeedocument'),
        ('tenancy', '0014_add_show_company_name_on_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='submitted_for_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_bonus',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_overtime',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='attendance_deduction',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='bonus_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='overtime_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='transfer_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='transfer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('bonus_type', models.CharField(choices=[('performance', 'Performance Bonus'), ('signing', 'Signing Bonus'), ('annual', 'Annual Bonus'), ('referral', 'Referral Bonus'), ('other', 'Other')], default='other', max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('applied', 'applied')], default='pending', max_length=20)),
                ('applied_in_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_bonuses', to='payroll.payrollrun')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave / Holiday'), ('holiday', 'Public Holiday')], default='present', max_length=20)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
