# Generated by Django 5.1.4 on 2026-07-02 11:48

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_employeetaxprofile_payeremittance'),
        ('tenancy', '0028_add_strict_gl_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payeremittance',
            name='unique_paye_remittance_per_org_period',
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_rent',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeetaxprofile',
            name='life_assurance_premium',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Monthly life assurance premium (pre-tax deductible)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='employeetaxprofile',
            name='nhf_enrolled',
            field=models.BooleanField(default=False, help_text='Employee has opted into NHF (2.5% of basic, voluntary)'),
        ),
        migrations.AlterField(
            model_name='employeetaxprofile',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='employeetaxprofile',
            name='paye_exempt',
            field=models.BooleanField(default=False, help_text='If True, no PAYE is deducted (e.g., expatriate relief, diplomatic exemption)'),
        ),
        migrations.AlterField(
            model_name='employeetaxprofile',
            name='voluntary_pension',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Additional voluntary pension contributions per month', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payeremittance',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='payeremittance',
            name='reference',
            field=models.CharField(blank=True, help_text='FIRS payment reference / TaxPro MAX schedule ref', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='payeremittance',
            unique_together={('organisation', 'period_year', 'period_month')},
        ),
    ]
