# Generated by Django 5.1.4 on 2026-07-06 17:40

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_nta2025_annual_rent_nhf_optin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='rent_relief',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
