# Generated by Django 5.1.4 on 2026-08-01 01:44

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_paye_remittances(apps, schema_editor):
    """
    Carry every PAYERemittance row into StatutoryRemittance.

    References already filed with an authority must survive the model swap, so
    reference / remittance_date / amount_paid are copied verbatim. The old model
    named FIRS as the recipient, which was wrong -- the rows land with no
    tax_authority set and a recipient label that tells the user to assign one.
    """
    PAYERemittance = apps.get_model('payroll', 'PAYERemittance')
    StatutoryRemittance = apps.get_model('payroll', 'StatutoryRemittance')

    rows = []
    for old in PAYERemittance.objects.all().iterator():
        rows.append(StatutoryRemittance(
            organisation_id=old.organisation_id,
            payroll_run_id=old.payroll_run_id,
            remittance_type='paye',
            period_year=old.period_year,
            period_month=old.period_month,
            tax_authority=None,
            recipient_name='State Internal Revenue Service (assign state of residence)',
            basis='Migrated from PAYE remittance tracker',
            amount_due=old.amount_due,
            amount_paid=old.amount_paid,
            status=('remitted' if old.status == 'remitted' else 'pending'),
            due_date=old.due_date,
            remittance_date=old.remittance_date,
            reference=old.reference,
            notes=old.notes,
        ))
    if rows:
        StatutoryRemittance.objects.bulk_create(rows, batch_size=500)


def unmigrate_paye_remittances(apps, schema_editor):
    """Reverse leg: drop the migrated PAYE rows so the forward leg can re-run."""
    StatutoryRemittance = apps.get_model('payroll', 'StatutoryRemittance')
    StatutoryRemittance.objects.filter(
        basis='Migrated from PAYE remittance tracker'
    ).delete()


def backfill_compensation(apps, schema_editor):
    """
    Give every existing employee one CompensationRecord dated at hire.

    Without this the effective-dated lookup finds nothing and falls back to the
    Employee columns -- which is correct, but leaves the history table empty and
    the first raise looking like the employee's only ever pay event.
    """
    Employee = apps.get_model('payroll', 'Employee')
    CompensationRecord = apps.get_model('payroll', 'CompensationRecord')

    existing = set(
        CompensationRecord.objects.values_list('employee_id', flat=True)
    )
    rows = []
    for emp in Employee.objects.all().iterator():
        if emp.id in existing or not emp.hire_date:
            continue
        rows.append(CompensationRecord(
            organisation_id=emp.organisation_id,
            employee_id=emp.id,
            effective_date=emp.hire_date,
            reason='hire',
            basic_salary=emp.basic_salary,
            housing_allowance=emp.housing_allowance,
            transport_allowance=emp.transport_allowance,
            leave_allowance=emp.leave_allowance,
            other_allowances=emp.other_allowances,
            notes='Backfilled from the employee record when compensation history was introduced.',
        ))
    if rows:
        CompensationRecord.objects.bulk_create(rows, batch_size=500, ignore_conflicts=True)


def unbackfill_compensation(apps, schema_editor):
    CompensationRecord = apps.get_model('payroll', 'CompensationRecord')
    CompensationRecord.objects.filter(reason='hire').delete()


def backfill_run_periods(apps, schema_editor):
    """
    Stamp period_start / period_end on historical runs.

    Proration divides by the number of working days in the period, so a run with
    no window would produce a zero factor and pay nobody.
    """
    import calendar

    from datetime import date

    PayrollRun = apps.get_model('payroll', 'PayrollRun')
    for run in PayrollRun.objects.filter(period_start__isnull=True).iterator():
        last_day = calendar.monthrange(run.period_year, run.period_month)[1]
        run.period_start = date(run.period_year, run.period_month, 1)
        run.period_end = date(run.period_year, run.period_month, last_day)
        # Historical runs are all regular monthly runs.
        if not run.run_number or '-R' not in run.run_number:
            run.run_number = f"PAY-{run.period_year}-{run.period_month:02d}-R1"
        run.save(update_fields=['period_start', 'period_end', 'run_number'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_payslipline_rent_relief'),
        ('tenancy', '0034_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-period_year', '-period_month', 'run_type', 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(blank=True, help_text='End of probation', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('', 'Not specified')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, help_text='Job grade / level', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('', 'Not specified')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_pin',
            field=models.CharField(blank=True, help_text='RSA PIN issued by the PFA', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='state_of_residence',
            field=models.CharField(blank=True, choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara'), ('FC', 'FCT Abuja')], default='', help_text="Determines which State IRS this employee's PAYE is remitted to", max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pay_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='run_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('off_cycle', 'Off-cycle'), ('supplementary', 'Supplementary'), ('thirteenth_month', '13th Month'), ('final_settlement', 'Final Settlement')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_benefits',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_benefits_employer',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_itf',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='adjustment_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Arrears / back-pay applied in this run', max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='advance_deductions',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Salary advance (EWA) recovered this period', max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='benefit_deductions',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Employee share of benefit premiums', max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='benefit_employer_cost',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Employer share (not deducted from net)', max_digits=15),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='days_in_period',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='days_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='proration_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='run_number',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('organisation', 'period_year', 'period_month', 'run_type', 'sequence')},
        ),
        migrations.CreateModel(
            name='AdvancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('max_percent_of_accrued', models.DecimalField(decimal_places=2, default=50, help_text='Cap as a percentage of net pay accrued so far this period', max_digits=5)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fee charged on the advanced amount', max_digits=5)),
                ('min_amount', apps.core.models.MoneyField(decimal_places=4, default=5000, max_digits=15)),
                ('max_requests_per_period', models.PositiveSmallIntegerField(default=1)),
                ('min_months_employed', models.PositiveSmallIntegerField(default=3)),
                ('require_approval', models.BooleanField(default=True)),
                ('min_cash_buffer', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Block approvals when bank balance would fall below this', max_digits=15)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name_plural': 'Advance policies',
            },
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('fee', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('total_recoverable', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('recovered', 'Recovered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accrued_at_request', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('days_worked_at_request', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_recovered', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('recovered_in_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_advances', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('benefit_type', models.CharField(choices=[('hmo', 'Health / HMO'), ('life', 'Group life assurance'), ('gym', 'Wellness / gym'), ('transport', 'Transport'), ('other', 'Other')], default='hmo', max_length=20)),
                ('provider_name', models.CharField(max_length=200)),
                ('basis', models.CharField(choices=[('fixed', 'Fixed amount per month'), ('percent_gross', 'Percentage of gross')], default='fixed', max_length=20)),
                ('employee_contribution', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('remittance_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the following month the premium is due')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('reason', models.CharField(choices=[('hire', 'Hire'), ('review', 'Annual review'), ('promotion', 'Promotion'), ('adjustment', 'Adjustment'), ('demotion', 'Demotion')], default='adjustment', max_length=20)),
                ('basic_salary', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('housing_allowance', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('transport_allowance', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('leave_allowance', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('other_allowances', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('employee', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_contribution_override', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('employer_contribution_override', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tier', models.CharField(blank=True, help_text='e.g. Individual, Family', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='payroll.benefitplan')),
            ],
            options={
                'ordering': ['plan__name'],
                'unique_together': {('employee', 'plan', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('days_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('accrual_method', models.CharField(choices=[('annual_grant', 'Granted in full at the start of the year'), ('monthly_accrual', 'Accrues monthly')], default='annual_grant', max_length=20)),
                ('is_paid', models.BooleanField(default=True, help_text='Unpaid leave falls through to the attendance deduction in payroll')),
                ('carry_forward_max', models.DecimalField(decimal_places=2, default=0, help_text='Maximum unused days that roll into the next year', max_digits=6)),
                ('gender_restriction', models.CharField(blank=True, choices=[('', 'None'), ('male', 'Male only'), ('female', 'Female only')], default='', max_length=10)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False, help_text='e.g. a medical certificate for extended sick leave')),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, default=0, help_text='Working days (weekends excluded), computed on save', max_digits=6)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='payroll.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('accrued_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('taken_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, help_text='Days in submitted-but-unapproved requests, held against the balance', max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='payroll.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_type', models.CharField(choices=[('arrears', 'Salary arrears'), ('backpay', 'Back pay'), ('correction', 'Correction')], default='arrears', max_length=20)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Positive to pay, negative to claw back', max_digits=15)),
                ('reason', models.CharField(max_length=500)),
                ('effective_period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_period_month', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('applied_in_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='payroll.payrollrun')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('itf_applicable', models.BooleanField(default=False)),
                ('itf_auto_assert', models.BooleanField(default=True, help_text='Turn ITF on automatically once headcount reaches 5')),
                ('nsitf_applicable', models.BooleanField(default=True)),
                ('default_pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=10)),
                ('leave_seeded', models.BooleanField(default=False)),
                ('tax_authorities_seeded', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name_plural': 'Payroll settings',
            },
        ),
        migrations.CreateModel(
            name='PayslipDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('portal', 'Portal'), ('download', 'Manual download')], default='email', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='sent', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='payroll.payslipline')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payslip deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('state_code', models.CharField(choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara'), ('FC', 'FCT Abuja')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('portal_url', models.URLField(blank=True)),
                ('payer_id', models.CharField(blank=True, help_text="The employer's registration / payer ID with this authority", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name_plural': 'Tax authorities',
                'ordering': ['name'],
                'unique_together': {('organisation', 'state_code')},
            },
        ),
        migrations.CreateModel(
            name='StatutoryRemittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('remittance_type', models.CharField(choices=[('paye', 'PAYE Tax'), ('pension', 'Pension'), ('nhf', 'National Housing Fund'), ('nsitf', 'NSITF / Employee Compensation'), ('itf', 'Industrial Training Fund'), ('benefit', 'Benefit Premium')], max_length=20)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('basis', models.CharField(blank=True, help_text='Rate / basis description', max_length=200)),
                ('amount_due', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('amount_paid', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially remitted'), ('remitted', 'Remitted')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('remittance_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Payment reference / schedule ref', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('gl_cleared', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='payroll.payrollrun')),
                ('tax_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittances', to='payroll.taxauthority')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'remittance_type', 'recipient_name'],
            },
        ),
        migrations.AddField(
            model_name='payslipline',
            name='tax_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.taxauthority'),
        ),
        migrations.RunPython(
            backfill_run_periods, noop, elidable=False,
        ),
        migrations.RunPython(
            backfill_compensation, unbackfill_compensation, elidable=False,
        ),
        migrations.RunPython(
            migrate_paye_remittances, unmigrate_paye_remittances, elidable=False,
        ),
        migrations.DeleteModel(
            name='PAYERemittance',
        ),
        migrations.AddIndex(
            model_name='statutoryremittance',
            index=models.Index(fields=['organisation', 'status'], name='payroll_sta_organis_2e6797_idx'),
        ),
        migrations.AddIndex(
            model_name='statutoryremittance',
            index=models.Index(fields=['organisation', 'due_date'], name='payroll_sta_organis_c06578_idx'),
        ),
    ]
