# Generated by Django 5.1.15 on 2026-08-07 00:28

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_payrollrun_options_and_more'),
        ('tenancy', '0035_partneraccessrequest_scope_alter_invitation_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_documents_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_overbooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='overbooked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_overbooked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='overbooked_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='gratuity_rate_per_year',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='leave_accrual_last_posted_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='leave_accrual_last_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='public_holidays_seeded_years',
            field=models.JSONField(blank=True, default=list, help_text='Years for which fixed-date public holidays have been seeded'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='thirteenth_month_basis',
            field=models.CharField(choices=[('basic', 'Basic salary'), ('gross', 'Gross salary')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('cv', 'CV / Resume'), ('id', 'ID Card / Passport'), ('certificate', 'Certificate / Qualification'), ('contract', 'Employment Contract'), ('work_permit', 'Work Permit / Visa'), ('professional_licence', 'Professional Licence'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('arrears', 'Salary arrears'), ('backpay', 'Back pay'), ('correction', 'Correction'), ('encashment', 'Leave encashment')], default='arrears', max_length=20),
        ),
        migrations.CreateModel(
            name='OffboardingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('resignation', 'Resignation'), ('dismissal_misconduct', 'Dismissal — misconduct'), ('dismissal_performance', 'Dismissal — performance'), ('redundancy', 'Redundancy'), ('contract_end', 'Contract end'), ('retirement', 'Retirement'), ('death_in_service', 'Death in service')], max_length=30)),
                ('last_working_day', models.DateField()),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_cases_completed', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_cases', to='payroll.employee')),
                ('final_settlement_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_cases', to='payroll.payrollrun')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_cases_initiated', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-last_working_day'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reasons_for_leaving', models.JSONField(blank=True, default=list, help_text='List of REASON_CHOICES values')),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True, help_text="If True, feedback is visible only to HR/owner/admin roles, never to the employee's manager")),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='payroll.offboardingcase')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=300)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_items_cleared', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='payroll.offboardingcase')),
            ],
            options={
                'ordering': ['order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=300)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('is_recurring_annually', models.BooleanField(default=True, help_text='Fixed-date holiday that recurs every year on this month/day')),
                ('applies_to_states', models.JSONField(blank=True, default=list)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('organisation', 'date', 'name')},
            },
        ),
    ]
