# Generated by Django 5.1.4 on 2026-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_employeedocument_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_alert_thresholds_sent',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
