# Generated by Django 5.1.15 on 2026-08-07 07:27

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_employeedocument_expiry_alert_thresholds_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='total_encashment',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
