# Generated by Django 5.1.4 on 2026-08-07 08:11

import apps.payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_payrollrun_total_encashment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.payroll.models._employee_doc_path),
        ),
    ]
