# Generated by Django 5.1.4 on 2026-08-09 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_employeedocument_file_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='decision_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('settled', 'settled'), ('cancelled', 'cancelled'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
