# Generated by Django 5.1.4 on 2026-08-20 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_employeeloan_approved_at_employeeloan_approved_by_and_more'),
        ('tenancy', '0037_organisation_receipt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'employee_id'), name='uniq_employee_org_employee_id'),
        ),
    ]
