# Generated by Django 5.1.4 on 2026-04-21 14:16

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_secret_pending",
            field=apps.core.fields.EncryptedCharField(
                blank=True, default="", max_length=500
            ),
        ),
    ]
