# Generated by Django 5.1.4 on 2026-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_offline_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_version',
            field=models.CharField(blank=True, default='', help_text='Version (date) of the legal terms this user has accepted. Empty = not yet accepted.', max_length=20),
        ),
    ]
