# Generated by Django 5.1.4 on 2026-04-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_partner_plans'),
        ('subscriptions', '0013_enterprise_features_v2'),
    ]

    operations = [
    ]
