# Generated by Django 5.1.4 on 2026-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_free_plan_no_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
