# Generated by Django 5.1.15 on 2026-08-07 00:35

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_alter_plan_trial_days'),
        ('tenancy', '0035_partneraccessrequest_scope_alter_invitation_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', apps.core.models.MoneyField(decimal_places=4, default=0, help_text="One-time fee, in the org's currency", max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integration Product',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='expected_amount',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('integration', 'Integration purchase')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_history', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='provider',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='succeeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='OrganisationIntegrationEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, help_text="e.g. 'refunded', 'manual', 'payment_abandoned'", max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='subscriptions.integrationproduct')),
            ],
            options={
                'verbose_name': 'Organisation Integration Entitlement',
            },
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='integration_entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.organisationintegrationentitlement'),
        ),
        migrations.AddConstraint(
            model_name='paymenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), models.Q(('integration_entitlement__isnull', True), ('kind', 'subscription'), ('subscription__isnull', False)), models.Q(('integration_entitlement__isnull', False), ('kind', 'integration'), ('subscription__isnull', True)), _connector='OR'), name='payment_history_exactly_one_target_when_settled'),
        ),
        migrations.AddConstraint(
            model_name='organisationintegrationentitlement',
            constraint=models.UniqueConstraint(fields=('organisation', 'product'), name='one_entitlement_per_org_product'),
        ),
    ]
