# Generated by Django 5.1.15 on 2026-08-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
        ('subscriptions', '0023_integrationproduct_paymenthistory_expected_amount_and_more'),
        ('tenancy', '0036_membership_granted_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenthistory',
            name='payment_history_exactly_one_target_when_settled',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='connector_addon_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='connectors.connectoraddonsubscription'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('integration', 'Integration purchase'), ('connector_addon', 'Connector add-on subscription')], default='subscription', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), models.Q(('connector_addon_subscription__isnull', True), ('integration_entitlement__isnull', True), ('kind', 'subscription'), ('subscription__isnull', False)), models.Q(('connector_addon_subscription__isnull', True), ('integration_entitlement__isnull', False), ('kind', 'integration'), ('subscription__isnull', True)), models.Q(('connector_addon_subscription__isnull', False), ('integration_entitlement__isnull', True), ('kind', 'connector_addon'), ('subscription__isnull', True)), _connector='OR'), name='payment_history_exactly_one_target_when_settled'),
        ),
    ]
