# Generated by Django 5.1.15 on 2026-08-09 22:55

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_seed_integration_products'),
        ('tenancy', '0036_membership_granted_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('connector_key', models.CharField(choices=[('slack', 'Slack'), ('google_sheets', 'Google Sheets')], db_index=True, max_length=30)),
                ('nango_connection_id', models.CharField(blank=True, db_index=True, help_text="Nango's connection ID. Never a raw OAuth token — Nango holds those.", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('external_account_label', models.CharField(blank=True, help_text="Display label, e.g. Slack workspace name — shown as 'Connected as {label}'.", max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('billing_mode', models.CharField(choices=[('plan_quota', 'Plan quota'), ('paid_addon', 'Paid add-on')], default='plan_quota', max_length=20)),
                ('pending_session_token', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name': 'Connector Connection',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorAddonSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('connector_key', models.CharField(choices=[('slack', 'Slack'), ('google_sheets', 'Google Sheets')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], db_index=True, default='incomplete', max_length=20)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='₦4,500/month per connector (or annual equivalent).', max_digits=15)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='paystack', max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_subscription', to='connectors.connectorconnection')),
            ],
            options={
                'verbose_name': 'Connector Add-on Subscription',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorEventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='connectors.connectorconnection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_deliveries', to='integrations.domainevent')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'verbose_name': 'Connector Event Delivery',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='connectorconnection',
            constraint=models.UniqueConstraint(fields=('organisation', 'connector_key'), name='one_connection_per_org_connector'),
        ),
        migrations.AddConstraint(
            model_name='connectoraddonsubscription',
            constraint=models.UniqueConstraint(fields=('organisation', 'connector_key'), name='one_addon_per_org_connector'),
        ),
        migrations.AddConstraint(
            model_name='connectoreventdelivery',
            constraint=models.UniqueConstraint(fields=('connection', 'event'), name='one_delivery_per_connection_event'),
        ),
    ]
