# Generated by Django 5.1.15 on 2026-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectoraddonsubscription',
            name='connector_key',
            field=models.CharField(choices=[('slack', 'Slack'), ('google_sheets', 'Google Sheets'), ('google_drive', 'Google Drive'), ('google_calendar', 'Google Calendar'), ('telegram', 'Telegram')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='connectorconnection',
            name='connector_key',
            field=models.CharField(choices=[('slack', 'Slack'), ('google_sheets', 'Google Sheets'), ('google_drive', 'Google Drive'), ('google_calendar', 'Google Calendar'), ('telegram', 'Telegram')], db_index=True, max_length=30),
        ),
    ]
