import LegalShell from './LegalShell'

export default function TermsPage() {
  return (
    <LegalShell title="Terms & Conditions">
      <p>These Terms and Conditions of Use (the “Legal Terms”) constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you” or “User”), and <strong>Audity Technologies Limited</strong>, a company incorporated in the Federal Republic of Nigeria under the Companies and Allied Matters Act 2020 with registration number RC 9395403 and registered office at 14 First Unity Estate, Ajah, Lagos, Nigeria (“Audity”, “we”, “us”, or “our”), concerning your access to and use of the Audity platform, our website, and our web, desktop, and mobile applications, together with all related products and services (collectively, the “Services”).</p>

      <h2>1. Agreement to our Legal Terms</h2>
      <p>By creating an Account, accessing, or using the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
      <p>Supplemental terms and conditions or documents that may be posted on the Services from time to time are hereby expressly incorporated by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Legal Terms at any time and for any reason, and will alert you by updating the “Last updated” date. Where a change materially and adversely affects your rights, we will take reasonable steps to notify you in advance. You will be deemed to have accepted the changes by your continued use of the Services after the revised Legal Terms are posted.</p>
      <p>The Services are intended for users who are at least 18 years of age and who are business owners, employees, agents, accountants, or authorised representatives of a registered business or enterprise. Persons under the age of 18 are not permitted to register for or use the Services.</p>

      <h2>2. Definitions</h2>
      <p><strong>“Account”</strong> means the registered account, identified by your email address, that you create to access the Services. <strong>“Account Owner”</strong> means the individual or entity that creates an Organisation and holds the owner role. <strong>“Authorised User”</strong> means any individual an Account Owner (or a Partner) invites to access an Organisation. <strong>“Content”</strong> means all data, records, invoices, payroll data, ledgers, inventory and stock records, and other materials you or your Authorised Users input, upload, or generate through the Services. <strong>“NDPA”</strong> means the Nigeria Data Protection Act 2023 and its subsidiary regulations. <strong>“Organisation”</strong> means a business workspace within the Services under which your Content is segregated and access is controlled by roles and permissions. <strong>“Partner”</strong> means an accounting, bookkeeping, tax, or advisory firm or practitioner that subscribes to a Partner tier to manage the Services on behalf of client Organisations. <strong>“Subscription”</strong> means a paid or free plan, including the Free, Professional, Business, and Enterprise tiers for businesses, and the Partner Starter, Partner Pro, and Partner Agency tiers for Partners. <strong>“Third-Party Services”</strong> means services, integrations, and APIs operated by third parties that the Services connect to or rely upon.</p>

      <h2>3. Our Services</h2>
      <p>Audity provides cloud-based accounting, bookkeeping, inventory and stock management, payroll, tax-computation, invoicing, purchasing, and business-management software designed principally for small and medium-sized businesses operating in Nigeria and across Africa, accessible through our web application and our Audity desktop and mobile applications. The Services may include, without limitation: double-entry general ledger and financial reporting; VAT computation and record-keeping; payroll processing including PAYE, NHF, and pension deductions; withholding-tax, income-tax, and company-income-tax tools; inventory, stock, purchase-order, and multi-warehouse management; invoicing, quotations, proforma and recurring invoices; bank reconciliation and budgeting; payment collection through integrated payment processors; FIRS e-invoicing through an accredited System Integrator; bank account linking through licensed open banking providers; multi-user collaboration with role- and permission-based access; and artificial-intelligence-assisted explanatory and analytical features.</p>
      <p><strong>The Services are provided as software tools only.</strong> Audity is a technology company and not a firm of chartered accountants, tax practitioners, auditors, legal advisers, or financial advisers. Nothing in the Services constitutes accounting, audit, tax, investment, or legal advice, and the Services are not a substitute for the professional judgement of a licensed accountant or qualified adviser. You remain solely responsible for the accuracy, completeness, and lawfulness of your own financial records, tax filings, statutory remittances, and business decisions.</p>

      <h2>4. Intellectual Property Rights</h2>
      <h3>4.1 Our intellectual property</h3>
      <p>We are the owner or licensee of all intellectual property rights in the Services, including all source code, databases, functionality, software, designs, and the trademarks, logos, and brand elements associated with Audity (the “Marks”). Except as expressly permitted, no part of the Services and no Marks may be copied, reproduced, republished, reverse-engineered, decompiled, or otherwise exploited for any commercial purpose without our express prior written permission.</p>
      <h3>4.2 Your use of the Services</h3>
      <p>Subject to your compliance with these Legal Terms, including payment of all applicable fees, we grant you a non-exclusive, non-transferable, non-sublicensable, revocable licence for you and your Authorised Users to access and use the Services for your internal business purposes only.</p>
      <h3>4.3 Your Content</h3>
      <p>You retain all ownership rights in your Content. By using the Services, you grant Audity a worldwide, royalty-free, non-exclusive licence to host, store, reproduce, process, and transmit your Content solely to the extent necessary to operate, maintain, secure, and provide the Services to you, to comply with applicable law, and to enforce these Legal Terms.</p>
      <h3>4.4 Feedback</h3>
      <p>If you submit any feedback, suggestions, or recommendations (“Feedback”), you grant us a perpetual, irrevocable, worldwide, royalty-free licence to use and exploit such Feedback for any purpose without obligation or compensation to you.</p>

      <h2>5. User Representations</h2>
      <p>By using the Services, you represent and warrant that:</p>
      <ul>
        <li>all registration and account information you submit is true, accurate, current, and complete, and you will maintain its accuracy;</li>
        <li>you have the legal capacity and authority to enter into these Legal Terms and, where acting for a business, are duly authorised to bind that entity;</li>
        <li>where you invite Authorised Users, you are authorised to do so and will ensure each complies with these Legal Terms;</li>
        <li>you are not a minor in the jurisdiction in which you reside;</li>
        <li>you will not access the Services through automated or non-human means except through interfaces we expressly authorise;</li>
        <li>you will not use the Services for any illegal or unauthorised purpose, including money laundering, terrorism financing, tax evasion, fraud, or the falsification of financial records; and</li>
        <li>your use will not violate any applicable law, including the NDPA, the Federal Competition and Consumer Protection Act 2018, the Money Laundering (Prevention and Prohibition) Act 2022, the Cybercrimes Act 2015, and applicable tax legislation.</li>
      </ul>

      <h2>6. Account Registration, Organisations, and Team Members</h2>
      <p>To use the Services you must register for an Account using a valid email address and password. You are solely responsible for all activity under your Account and for maintaining the security of your credentials, and you agree to notify us immediately of any unauthorised access. The Account Owner is responsible for determining and reviewing each Authorised User’s role and access, ensuring each is authorised, and for all acts and omissions of its Authorised Users. You are responsible for promptly removing any Authorised User who should no longer have access. We reserve the right to reclaim or require you to change any Organisation name or identifier we reasonably determine to be inappropriate, infringing, or objectionable.</p>

      <h2>7. Subscriptions, Fees, and Payment</h2>
      <p>The Services are offered across a free tier and the paid Professional, Business, and Enterprise tiers for businesses, and the Partner Starter, Partner Pro, and Partner Agency tiers for Partners. Where you select a paid Subscription, you agree to pay all applicable fees in Nigerian Naira at the prices then in effect, exclusive of applicable taxes including VAT.</p>
      <p><strong>Billing and renewal.</strong> Billing is recurring on a monthly or annual basis, and your Subscription automatically renews until cancelled. You authorise us and our payment processor to charge your payment method for all fees due, including on renewal. If a charge is declined, we may suspend or downgrade access until payment is received.</p>
      <p><strong>Free tier.</strong> The free tier is provided at no charge with reduced features and lower limits; we may modify, limit, or discontinue it on reasonable notice. We may correct pricing errors and change fees on prospective renewal on not less than thirty (30) days’ notice.</p>
      <p><strong>Refunds.</strong> Except where required by the Federal Competition and Consumer Protection Act 2018 or other applicable law, fees paid are non-refundable. On cancellation you retain paid features until the end of the current billing period. Your statutory rights as a consumer are not affected.</p>

      <h2>8. Partner and Accountant Program</h2>
      <p>If you subscribe to a Partner tier, you may create, access, and manage Organisations on behalf of your clients (each a “Client Organisation”), subject to the features and limits of your tier. For each Client Organisation, you represent that you are duly authorised by the client to do so and to process that client’s Content. Audity provides software to you and your clients; we are not a party to, and are not responsible for, the professional engagement between you and your clients. Where you process a Client Organisation’s data, you do so as that client’s agent or processor and Audity acts as processor or sub-processor as applicable. You may not resell or sublicense the Services except as expressly permitted by your Partner tier or a separate written agreement, and on termination you are responsible for transitioning each Client Organisation to the relevant client.</p>

      <h2>9. Prohibited Activities</h2>
      <p>You may use the Services only for lawful business purposes. You agree that you shall NOT: use the Services to record, generate, conceal, or facilitate any false, fraudulent, or misleading financial records, invoices, tax returns, or filings, or to evade any tax obligation; use them in connection with money laundering or terrorism financing; access any Organisation, Content, or Account you are not authorised to access; exceed or circumvent any usage or access limit of your tier; systematically retrieve data to compile a database without permission; circumvent, disable, reverse-engineer, or interfere with security features; trick or defraud us or other users; use the Services to build a competing product; upload malicious code; upload Content you do not have the lawful right to process; or use the Services in any manner that could disable, overburden, or impair them or interfere with other users.</p>

      <h2>10. Third-Party Services and Integrations</h2>
      <p>The Services integrate with and rely upon Third-Party Services, including payment processors, licensed open banking providers, AI providers, and accredited e-invoicing System Integrators. Your use of any Third-Party Service is governed by that third party’s own terms and privacy policies. <strong>Audity does not control, and is not responsible or liable for, the acts, omissions, availability, accuracy, security, or performance of any Third-Party Service,</strong> including any delay, rejection, or failure in the transmission of invoices, payments, bank data, or filings by any processor, provider, integrator, or authority including FIRS.</p>

      <h2>11. Financial, Accounting, and Tax Disclaimer</h2>
      <p className="lead-caps"><strong>THE SERVICES ARE ACCOUNTING AND COMPLIANCE SOFTWARE TOOLS. AUDITY DOES NOT PROVIDE ACCOUNTING, AUDIT, TAX, LEGAL, OR FINANCIAL ADVICE, AND ANY REPORTS, COMPUTATIONS, EXPLANATIONS, OR AI-GENERATED OUTPUTS PRODUCED THROUGH THE SERVICES ARE FOR INFORMATIONAL PURPOSES ONLY.</strong></p>
      <p>You acknowledge and agree that: you are solely responsible for the accuracy, completeness, timeliness, and lawfulness of all financial records, invoices, payroll computations, VAT, PAYE, and withholding-tax calculations, tax returns, and filings prepared with or transmitted through the Services; all outputs, including AI features, may contain errors and must be independently reviewed and verified by you and, where appropriate, by a qualified accountant or tax practitioner before you rely on them or submit them to any authority; and you remain solely responsible for meeting all filing deadlines and remittance obligations to FIRS, State Internal Revenue Services, pension fund administrators, and any other authority. <strong>To the fullest extent permitted by law, Audity shall not be liable for any tax penalty, interest, fine, assessment, loss, or liability arising from any error, omission, or inaccuracy in your financial records or filings, or from your reliance on any output of the Services.</strong></p>

      <h2>12. Artificial Intelligence Features</h2>
      <p>The Services may include AI-assisted features that generate explanations, summaries, categorisations, or analytical insights (“AI Outputs”). AI Outputs are generated by automated models for informational and convenience purposes only, may be inaccurate, incomplete, or misleading, and do not constitute accounting, tax, legal, or financial advice. You must independently review and verify any AI Output before relying on it. We do not warrant that AI features will be available, uninterrupted, accurate, or fit for any purpose, and we may change, limit, or discontinue them at any time.</p>

      <h2>13. Data Protection and Privacy</h2>
      <p>Audity processes personal data in accordance with the NDPA and applicable data protection law, and, where applicable, the GDPR. Our collection and use of personal data is described in our Privacy Policy, incorporated by reference. Where you upload or process the personal data of your own employees, customers, or third parties, you act as the data controller and Audity acts as a data processor on your behalf; you represent that you have a lawful basis and have provided all notices and obtained all consents required. The rights and obligations of the parties are set out in our Data Processing Agreement. We implement reasonable technical and organisational measures to protect personal data, and in the event of a personal data breach we will act in accordance with the NDPA, including notifying the NDPC and affected data subjects as required.</p>

      <h2>14. Your Data, Backup, and Retention</h2>
      <p>While we take reasonable measures to protect and back up data, you are responsible for maintaining your own copies of critical business and financial records and for exporting your Content at regular intervals. The Services are not intended to be your sole system of record or backup of last resort. You may export certain Content in the formats we provide, and on termination you may request an export within thirty (30) days. We retain Content while your Account is active and thereafter as required to provide the Services, comply with law, resolve disputes, and enforce our agreements; some data may persist in backups for a limited period before being overwritten.</p>

      <h2>15. Services Management</h2>
      <p>We reserve the right, but not the obligation, to monitor the Services for violations; take appropriate legal action against violators; refuse, restrict, or disable Content we reasonably determine to be unlawful, infringing, or in breach; remove excessive or burdensome files with reasonable notice where practicable; and otherwise manage the Services to protect our rights, other users, and the proper functioning and security of the Services.</p>

      <h2>16. Beta and Early-Access Features</h2>
      <p>We may offer features identified as beta, preview, early-access, or trial (“Beta Features”). Beta Features are provided “as is” and “as available” for evaluation, may be changed or withdrawn at any time, may be unstable or contain errors, and are excluded from any service commitment, warranty, or indemnity to the fullest extent permitted by law. You use Beta Features at your own risk and should not rely on them for critical business or compliance purposes.</p>

      <h2>17. Term and Termination</h2>
      <p>These Legal Terms remain in effect while you use the Services. You may terminate at any time by cancelling your Subscription and ceasing use. We may suspend or terminate your access with immediate effect where you materially breach these Legal Terms (and fail to remedy a remediable breach within a reasonable period after notice); use the Services unlawfully or in a way that exposes Audity or its users to liability or security risk; where required by law or a competent authority; where continued provision becomes impracticable; or where you fail to pay fees when due. Where circumstances permit we will give reasonable prior notice and an opportunity to remedy; where the breach is serious or unlawful we may act without notice. Clauses which by their nature should survive termination — including intellectual property, disclaimers, limitation of liability, indemnification, and governing law — shall survive.</p>

      <h2>18. Modifications and Interruptions</h2>
      <p>We may change, modify, suspend, or discontinue all or any part of the Services at any time for legitimate operational, technical, legal, or commercial reasons. Where you have prepaid for a Subscription and we permanently discontinue it, we will provide a pro-rata refund for the unused portion. We cannot guarantee the Services will be available at all times and have no liability for any loss caused by downtime or discontinuance, except as expressly provided in a written service level agreement.</p>

      <h2>19. Disclaimer of Warranties</h2>
      <p className="lead-caps"><strong>TO THE FULLEST EXTENT PERMITTED BY LAW, THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</strong></p>
      <p>We make no warranty that the Services will meet your requirements, be uninterrupted, timely, secure, or error-free. We do not warrant the accuracy, completeness, or reliability of any output, including AI-generated content. Nothing in this clause excludes any warranty or remedy that cannot be excluded under the Federal Competition and Consumer Protection Act 2018 or other applicable Nigerian law, and your statutory rights as a consumer are not affected.</p>

      <h2>20. Limitation of Liability</h2>
      <p>Nothing in these Legal Terms excludes or limits our liability for: (a) death or personal injury caused by our negligence; (b) fraud or fraudulent misrepresentation; or (c) any other liability that cannot lawfully be excluded, including under the Federal Competition and Consumer Protection Act 2018.</p>
      <p>Subject to the paragraph above, and to the fullest extent permitted by law, Audity shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, revenue, data, goodwill, or business opportunity. Our total aggregate liability arising out of or in connection with these Legal Terms and your use of the Services shall not exceed the greater of (i) the total fees actually paid by you to Audity in the six (6) months preceding the event giving rise to the claim, or (ii) thirty thousand Naira (₦30,000). Where you use the Services under a free plan and have paid no fees, our aggregate liability shall be nil (₦0), subject to the carve-outs above.</p>

      <h2>21. Indemnification</h2>
      <p>You agree to defend, indemnify, and hold harmless Audity and its directors, officers, employees, and agents from any loss, liability, claim, damages, cost, or expense (including reasonable legal fees) arising out of or relating to: your use of the Services; your breach of these Legal Terms or any representation or warranty; your violation of the rights of any third party; any Content you or your Authorised Users upload or process; or any tax, regulatory, or statutory liability arising from your own filings, records, or remittances. This indemnity does not apply to the extent a loss arises directly from our own proven negligence, wilful misconduct, or breach.</p>

      <h2>22. Electronic Communications, Transactions, and Signatures</h2>
      <p>By using the Services and communicating with us electronically, you consent to receive communications electronically and agree that electronic agreements, notices, and disclosures satisfy any legal requirement that such communication be in writing. You agree to the use of electronic records and signatures and acknowledge that, under the Evidence Act 2011, electronic records and signatures may be admissible and enforceable.</p>

      <h2>23. Governing Law</h2>
      <p>These Legal Terms and any dispute or claim arising out of or in connection with them (including non-contractual disputes) are governed by and construed in accordance with the laws of the Federal Republic of Nigeria.</p>

      <h2>24. Dispute Resolution</h2>
      <p>The parties shall first seek to resolve any dispute amicably through good-faith negotiation. If not resolved within thirty (30) days of written notice, either party may refer the dispute to mediation or, failing that, to arbitration in Lagos, Nigeria, under the Arbitration and Mediation Act 2023, before a sole arbitrator, in English. Nothing prevents either party from seeking urgent injunctive relief from a competent court, or a consumer from complaining to the Federal Competition and Consumer Protection Commission or other competent authority.</p>

      <h2>25. Miscellaneous</h2>
      <p>These Legal Terms, together with documents incorporated by reference, constitute the entire agreement between you and Audity and supersede prior understandings. If any provision is held unenforceable, it shall be severed and the remainder shall continue in effect. You may not assign these Legal Terms without our written consent; we may assign to an affiliate or successor on notice. No failure to exercise a right operates as a waiver. We are not liable for delay or failure caused by events beyond our reasonable control. Nothing creates any partnership, joint venture, agency, or employment relationship, and a person who is not a party has no right to enforce these terms.</p>

      <h2>26. Contact Us</h2>
      <p>Audity Technologies Limited · 14 First Unity Estate, Ajah, Lagos, Nigeria · Email: info@auditytechnologies.com · Website: auditytechnologies.com</p>
    </LegalShell>
  )
}
