# Generated by Django 5.1.4 on 2026-07-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_backfill_control_account_flags'),
        ('suppliers', '0002_supplier_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='GL control account for this supplier. Leave blank to use the organisation default.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='accounting.account'),
        ),
    ]
