# Generated by Django 5.1.4 on 2026-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_backfill_control_account_flags'),
        ('suppliers', '0003_supplier_payable_account'),
        ('tenancy', '0037_organisation_receipt_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organisation', 'code'), name='uniq_supplier_org_code'),
        ),
    ]
