# Generated by Django 5.1.4 on 2026-03-07 10:35

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='unit_price',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period_type',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('annual', 'annual')], default='monthly', max_length=20),
        ),
    ]
