# Generated by Django 5.1.15 on 2026-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_period_and_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
