# Generated by Django 5.1.15 on 2026-09-06 14:29

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budget_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='budget_line_attachments/'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='forecast_amount',
            field=apps.core.models.MoneyField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
