# Generated by Django 5.1.4 on 2026-08-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_seed_integration_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Subscription'},
        ),
    ]
