from django.urls import path
from .views import (
    APAgingView,
    ARAgingView,
    AccountStatementView,
    CashFlowView,
    CustomerBalanceView,
    CustomerDetailsView,
    CustomerInvoicesView,
    CustomerPaymentsView,
    ExpenseBreakdownView,
    InventoryValuationView,
    PaymentMethodsView,
    PaymentsByCustomerView,
    ProductDetailsView,
    ProfitAndLossView,
    SalesByCustomerView,
    SalesByProductView,
    SalesSummaryView,
    TopCustomersView,
    TopProductsView,
    VATSummaryView,
    ReportBulkExportView,
    ReportCatalogView,
    ReportDispatchView,
)

urlpatterns = [
    path("catalog/", ReportCatalogView.as_view(), name="report-catalog"),
    path("r/<str:key>/", ReportDispatchView.as_view(), name="report-dispatch"),
    path("export-bulk/", ReportBulkExportView.as_view(), name="report-export-bulk"),
    path("sales/", SalesSummaryView.as_view(), name="report-sales"),
    path("top-products/", TopProductsView.as_view(), name="report-top-products"),
    path("top-customers/", TopCustomersView.as_view(), name="report-top-customers"),
    path("pnl/", ProfitAndLossView.as_view(), name="report-pnl"),
    path("expenses/", ExpenseBreakdownView.as_view(), name="report-expenses"),
    path("inventory/", InventoryValuationView.as_view(), name="report-inventory"),
    path("cash-flow/", CashFlowView.as_view(), name="report-cash-flow"),
    path("ar-aging/", ARAgingView.as_view(), name="report-ar-aging"),
    path("ap-aging/", APAgingView.as_view(), name="report-ap-aging"),
    path("vat-summary/", VATSummaryView.as_view(), name="report-vat-summary"),
    path("sales-by-customer/", SalesByCustomerView.as_view(), name="report-sales-by-customer"),
    path("sales-by-product/", SalesByProductView.as_view(), name="report-sales-by-product"),
    path("payment-methods/", PaymentMethodsView.as_view(), name="report-payment-methods"),
    path("customer-balance/", CustomerBalanceView.as_view(), name="report-customer-balance"),
    path("payments-by-customer/", PaymentsByCustomerView.as_view(), name="report-payments-by-customer"),
    path("customer-payments/", CustomerPaymentsView.as_view(), name="report-customer-payments"),
    path("customer-invoices/", CustomerInvoicesView.as_view(), name="report-customer-invoices"),
    path("account-statement/", AccountStatementView.as_view(), name="report-account-statement"),
    path("customer-details/", CustomerDetailsView.as_view(), name="report-customer-details"),
    path("product-details/", ProductDetailsView.as_view(), name="report-product-details"),
]
