# Generated by Django 5.1.4 on 2026-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('distributor', 'Distributor'), ('corporate', 'Corporate'), ('client', 'Client'), ('passenger', 'Passenger'), ('vip', 'VIP'), ('government', 'Government'), ('ngo', 'NGO')], default='retail', max_length=20),
        ),
    ]
