# Generated by Django 5.1.4 on 2026-07-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_backfill_control_account_flags'),
        ('customers', '0006_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivable_account',
            field=models.ForeignKey(blank=True, help_text='GL control account for this customer. Leave blank to use the organisation default.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounting.account'),
        ),
    ]
