# Generated by Django 5.1.4 on 2026-08-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
