# Generated by Django 5.1.4 on 2026-07-31 17:33

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_inventory_account'),
        ('pos', '0001_initial'),
        ('tenancy', '0033_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TillSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_float', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Cash in the drawer at the start.', max_digits=15)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('cash_variance', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='Counted minus expected. Negative is short.', max_digits=15)),
                ('variance_reason', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='till_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Which shop or counter this till belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='till_sessions', to='inventory.warehouse')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='till_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-opened_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TillTenderCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(max_length=20)),
                ('expected', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('counted', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('variance', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_counts', to='pos.tillsession')),
            ],
            options={
                'ordering': ['method'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='tillsession',
            index=models.Index(fields=['organisation', 'status'], name='pos_tillses_organis_e7ed14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tilltendercount',
            unique_together={('session', 'method')},
        ),
    ]
