# Generated by Django 5.1.4 on 2026-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_tillsession_tilltendercount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tillsession',
            name='gl_post_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tillsession',
            name='gl_post_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed'), ('not_configured', 'Not configured')], default='pending', max_length=20),
        ),
    ]
