# Generated by Django 5.1.4 on 2026-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_tillsession_gl_post_error_tillsession_gl_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
