# Generated by Django 5.1.4 on 2026-07-31 15:31

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0018_add_transmitted_at_to_invoice'),
        ('tenancy', '0033_organisation_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='allow_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='allow_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='contract_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='preferred_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='use_sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='virtual_account_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify / Moniepoint'), ('flutterwave', 'Flutterwave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='public_key',
            field=models.CharField(blank=True, help_text='Public/API key. For Monnify this is the API key.', max_length=200),
        ),
        migrations.CreateModel(
            name='MerchantBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Offered first at checkout and printed on invoices.')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_invoice', models.BooleanField(default=True)),
                ('show_on_storefront', models.BooleanField(default=True)),
                ('instructions', models.CharField(blank=True, help_text="Shown under the account, e.g. 'Use your order number as the narration'.", max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-is_default', 'bank_name'],
                'unique_together': {('organisation', 'bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankTransferClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('narration', models.CharField(blank=True, max_length=200)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='transfer_proofs/')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='awaiting', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_claims', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_claims', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='payments.merchantbankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='payments_ba_organis_c75e94_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_event')],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='payments_vi_organis_f7bd70_idx')],
            },
        ),
    ]
