# Generated by Django 5.1.4 on 2026-08-01 11:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentgatewayconfig_allow_card_and_more'),
        ('sales', '0020_salepayment_till_session'),
        ('tenancy', '0033_organisation_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, help_text='Whose terminal these came from, e.g. Moniepoint, OPay.', max_length=40)),
                ('source', models.CharField(choices=[('upload', 'File upload'), ('provider', 'Provider feed')], default='upload', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('fee', apps.core.models.MoneyField(decimal_places=4, default=0, help_text='What the provider deducted.', max_digits=15)),
                ('terminal_id', models.CharField(blank=True, max_length=60)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('narration', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('unmatched', 'Needs review'), ('matched', 'Matched'), ('other_income', 'Recorded as other income'), ('ignored', 'Ignored')], db_index=True, default='unmatched', max_length=14)),
                ('matched_automatically', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.settlementbatch')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='sales.salepayment')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['organisation', 'status'], name='payments_se_organis_17972f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'provider_reference'), name='unique_settlement_reference')],
            },
        ),
    ]
