# Generated by Django 5.1.4 on 2026-03-03 09:42

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_product_type'),
        ('sales', '0002_recurringinvoice_recurringinvoicelog'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective / Damaged'), ('wrong_item', 'Wrong Item Delivered'), ('customer_change', 'Customer Changed Mind'), ('overcharge', 'Overcharge / Price Error'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('return_date', models.DateField()),
                ('total_refund', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('restocked', models.BooleanField(default=True, help_text='Whether items were physically returned to stock')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('refund_amount', apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
