# Generated by Django 5.1.4 on 2026-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_sale_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('proforma', 'Proforma'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('voided', 'Voided'), ('credit', 'Credit')], db_index=True, default='draft', max_length=20),
        ),
    ]
