# Generated by Django 5.1.4 on 2026-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoicefolder_invoice_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoice',
            name='custom_customer_name',
            field=models.CharField(blank=True, help_text='Free-text customer/vendor name when not in the customer list', max_length=255),
        ),
    ]
