# Generated by Django 5.1.4 on 2026-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_add_credit_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="quantity_returned",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cumulative quantity returned so far for this line item",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("proforma", "Proforma"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("partially_paid", "Partially Paid"),
                    ("overdue", "Overdue"),
                    ("voided", "Voided"),
                    ("credit", "Credit"),
                    ("returned", "Returned"),
                    ("partially_returned", "Partially Returned"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
