# Generated by Django 5.1.4 on 2026-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_add_return_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("proforma", "Proforma"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("partially_paid", "Partially Paid"),
                    ("overdue", "Overdue"),
                    ("voided", "Voided"),
                    ("credit", "Credit"),
                    ("returned", "Returned"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
