# Generated by Django 5.1.4 on 2026-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_invoice_sold_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
