# Generated by Django 5.1.4 on 2026-04-22 08:28
#
# AlterField with db_index=True generates CREATE INDEX which requires table
# ownership on Railway (PostgreSQL). Use SeparateDatabaseAndState so Django's
# model state is updated but the database operation is a graceful RunSQL that
# catches insufficient_privilege instead of aborting the whole migration run.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_invoice_sold_by"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="location",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            CREATE INDEX IF NOT EXISTS sales_location_created_at_idx
                                ON sales_location (created_at);
                        EXCEPTION WHEN insufficient_privilege THEN
                            RAISE NOTICE 'Skipping index on sales_location.created_at: insufficient privilege';
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
