# Generated by Django 5.1.4 on 2026-04-22 08:28
#
# AlterField with db_index=True generates CREATE INDEX which requires table
# ownership on Railway (PostgreSQL). Use SeparateDatabaseAndState so Django's
# model state is updated but the database operation is a graceful RunPython
# that skips on SQLite (tests) and catches insufficient_privilege on Postgres.

from django.db import migrations, models


def add_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cur:
        try:
            cur.execute("""
                DO $$
                BEGIN
                    CREATE INDEX IF NOT EXISTS sales_location_created_at_idx
                        ON sales_location (created_at);
                EXCEPTION WHEN insufficient_privilege THEN
                    RAISE NOTICE 'Skipping index on sales_location.created_at: insufficient privilege';
                END $$;
            """)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_invoice_sold_by"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="location",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_index, migrations.RunPython.noop, atomic=False),
            ],
        ),
    ]
