# Generated by Django 5.1.4 on 2026-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_invoice_firs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gl_post_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gl_post_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed'), ('not_configured', 'Not Configured')], default='pending', max_length=20),
        ),
    ]
