# Generated by Django 5.1.4 on 2026-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_gl_post_error_invoice_gl_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='When stock/GL were posted for a deferred invoice. Null = not yet fulfilled.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deferred',
            field=models.BooleanField(default=False, help_text='True if stock deduction + GL posting were deferred at creation time.'),
        ),
    ]
