# Generated by Django 5.1.4 on 2026-07-02 11:54

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoice_deferred_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturnitem',
            name='tax_refund',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
