# Generated by Django 5.1.4 on 2026-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_add_tax_refund_to_salereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transmitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when invoice was transmitted to FIRS for clearance.', null=True),
        ),
    ]
