# Generated by Django 5.1.4 on 2026-07-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_tillsession_tilltendercount_and_more'),
        ('sales', '0019_alter_salepayment_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='till_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.tillsession'),
        ),
    ]
