# Generated by Django 5.1.4 on 2026-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salepayment_till_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
