# Generated by Django 5.1.4 on 2026-08-28 04:04

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_saleitem_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_amount',
            field=apps.core.models.MoneyField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
