// Shared list of Nigerian banks (commercial, MFBs, mobile money / fintech) with Paystack bank codes.
// Consolidated from the previously duplicated lists in EmployeesPage.tsx and SettingsPage.tsx.
export interface NigerianBank {
  name: string
  code: string
}

export const NIGERIAN_BANKS: NigerianBank[] = [
  { name: '9 Payment Service Bank (9PSB)', code: '120005' },
  { name: 'AB Microfinance Bank', code: '309' },
  { name: 'Access Bank', code: '044' },
  { name: 'Accion MFB', code: '602' },
  { name: 'Airtel SmartCash PSB', code: '120004' },
  { name: 'Carbon (One Finance)', code: '565' },
  { name: 'Citibank Nigeria', code: '023' },
  { name: 'Covenant MFB', code: '551' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Fidelity Bank', code: '070' },
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'First City Monument Bank (FCMB)', code: '214' },
  { name: 'Globus Bank', code: '00103' },
  { name: 'Guaranty Trust Bank (GTBank)', code: '058' },
  { name: 'Heritage Bank', code: '030' },
  { name: 'Jaiz Bank', code: '301' },
  { name: 'Keystone Bank', code: '082' },
  { name: 'Kuda Microfinance Bank', code: '090267' },
  { name: 'LAPO Microfinance Bank', code: '501' },
  { name: 'Lotus Bank', code: '303' },
  { name: 'Moniepoint MFB', code: '50515' },
  { name: 'MTN Mobile Money (MoMo PSB)', code: '120001' },
  { name: 'NPF Microfinance Bank', code: '552' },
  { name: 'OPay Digital Services', code: '100004' },
  { name: 'Optimus Bank', code: '301' },
  { name: 'PalmPay', code: '999991' },
  { name: 'Parallex Bank', code: '526' },
  { name: 'Polaris Bank', code: '076' },
  { name: 'Premium Trust Bank', code: '105' },
  { name: 'Providus Bank', code: '101' },
  { name: 'Rubies MFB', code: '125' },
  { name: 'Sparkle MFB', code: '51310' },
  { name: 'Stanbic IBTC Bank', code: '221' },
  { name: 'Standard Chartered Bank', code: '068' },
  { name: 'Sterling Bank', code: '232' },
  { name: 'SunTrust Bank', code: '100' },
  { name: 'Taj Bank', code: '302' },
  { name: 'Titan Trust Bank', code: '102' },
  { name: 'Union Bank of Nigeria', code: '032' },
  { name: 'United Bank for Africa (UBA)', code: '033' },
  { name: 'Unity Bank', code: '215' },
  { name: 'VFD Microfinance Bank', code: '566' },
  { name: 'Wema Bank', code: '035' },
  { name: 'Zenith Bank', code: '057' },
].sort((a, b) => a.name.localeCompare(b.name))
