# Generated by Django 5.1.4 on 2026-02-23 14:46

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("debit", "Debit (Sale on Credit)"),
                            ("credit", "Credit (Payment Received)"),
                            ("adjustment", "Adjustment"),
                            ("write_off", "Write-Off"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "amount",
                    apps.core.models.MoneyField(
                        decimal_places=4,
                        default=0,
                        help_text="Always positive; sign determined by transaction_type",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_after",
                    apps.core.models.MoneyField(
                        decimal_places=4,
                        default=0,
                        help_text="Denormalised running balance for this customer",
                        max_digits=15,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_transactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_txns",
                        to="sales.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["customer", "created_at"],
                        name="credits_cre_custome_4f69f4_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="credits_cre_due_dat_4e3332_idx"
                    ),
                ],
            },
        ),
    ]
