# Generated by Django 5.1.4 on 2026-06-18 11:42

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_journal_immutability_trigger"),
        ("credits", "0001_initial"),
        ("inventory", "0008_product_hsn_digitax"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Resolved or manually entered remitter name",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="balance_before",
            field=apps.core.models.MoneyField(
                blank=True,
                decimal_places=4,
                default=0,
                help_text="Denormalised running balance prior to this entry",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="bank_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack bank code, for account resolution",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="credit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_transactions_credited",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_transactions_debited",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_transactions",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("pos", "POS"),
                    ("cheque", "Cheque"),
                    ("credit_applied", "Credit Applied"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="payment_number",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
